/*
 * This file was automatically generated by EvoSuite
 * Tue May 26 18:32:32 CEST 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.NullNode;
import com.fasterxml.jackson.databind.node.NumericNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.ValueNode;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import java.util.function.BiFunction;
import org.apache.avro.AvroRuntimeException;
import org.apache.avro.AvroTypeException;
import org.apache.avro.LogicalType;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.SchemaParseException;
import org.apache.avro.path.TracingAvroTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(resetStaticState = false, separateClassLoader = false) 
public class Schema_C1_ESTest extends Schema_C1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parseJsonToObject("$:H5<`K1qbQfM0y%>b");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token '$': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      boolean boolean0 = schema0.isNullable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
      Object[] objectArray0 = new Object[7];
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>(objectArray0);
      Schema.LockableArrayList<Object> schema_LockableArrayList1 = schema_LockableArrayList0.lock();
      // Undeclared exception!
      try { 
        schema_LockableArrayList1.removeAll(stack0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$LockableArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      NullNode nullNode0 = jsonNodeFactory0.nullNode();
      Set<String> set0 = Schema.parseAliases(nullNode0);
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("8UX*-;?", "8UX*-;?");
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
      assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("K", schema1, "Fs}]VPw", "K");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field K: \"K\" not a {\"type\":\"array\",\"items\":\"string\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createMap(schema0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("map", schema1, "4_CvjZ`_1et:=_", object0, schema_Field_Order0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field map: null not a {\"type\":\"map\",\"values\":{\"type\":\"record\",\"fields\":[]}}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("B", "", "t%'ELH?", (List<String>) arrayList0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertEquals("", schema0.getDoc());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      NullNode nullNode0 = jsonNodeFactory0.nullNode();
      Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
      Schema schema0 = Schema.create(schema_Type0);
      boolean boolean0 = schema0.isValidDefault(nullNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ValueNode valueNode0 = jsonNodeFactory0.pojoNode(linkedList0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      boolean boolean0 = schema0.isValidDefault((JsonNode) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("CAN_WRITE_BINARY_NATIVELY", schema0, "CAN_WRITE_BINARY_NATIVELY", "<*<!_(q1\"|", schema_Field_Order0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createFixed("BeDRm", "ma=", "ma=", 15);
      Schema.Names schema_Names0 = new Schema.Names();
      BiFunction<Object, Object, Schema> biFunction0 = (BiFunction<Object, Object, Schema>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      schema_Names0.merge((Schema.Name) null, schema1, biFunction0);
      // Undeclared exception!
      try { 
        schema_Names0.put((Schema.Name) null, schema0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Can't redefine: null
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Names schema_Names0 = new Schema.Names();
      BiFunction<Object, Object, Schema> biFunction0 = (BiFunction<Object, Object, Schema>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      schema_Names0.merge((Schema.Name) null, schema0, biFunction0);
      Schema schema1 = schema_Names0.put((Schema.Name) null, schema0);
      assertNull(schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum((String) null, "record", "record", (List<String>) linkedList0, (String) null);
      Schema.Names schema_Names0 = new Schema.Names("values");
      Schema.Name schema_Name0 = new Schema.Name((String) null, "record");
      schema_Names0.put(schema_Name0, schema0);
      boolean boolean0 = schema_Names0.contains(schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("fixed");
      Schema schema0 = Schema.createFixed("fixed", "uol.[*Lb", "fixed", 10);
      boolean boolean0 = schema_Names0.contains(schema0);
      assertFalse(boolean0);
      assertEquals("uol.[*Lb", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Names schema_Names0 = new Schema.Names("BeDRm");
      Schema.Name schema_Name0 = new Schema.Name("BeDRm", "BeDRm");
      schema_Names0.put(schema_Name0, schema0);
      Schema schema1 = schema_Names0.get("BeDRm");
      assertEquals(Schema.Type.UNION, schema1.getType());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema schema0 = schema_Names0.get("double");
      assertEquals(Schema.Type.DOUBLE, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("org.apache.avro.compiler.UnresolvedSchema_144");
      Schema schema0 = schema_Names0.get("org.apache.avro.compiler.UnresolvedSchema_144");
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Schema schema0 = Schema.parse("\"string\"", false);
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("[ \"string\" ]", stringArray0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // dangling content after end of schema: null
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      schema_Parser0.parseInternal("[\"string\"]");
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("{\n  \"type\" : \"record\",\n  \"fields\" : [ ]\n}", stringArray0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // No name in schema: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      List<Schema> list0 = List.of(schema0, schema0, schema0, schema0, schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // You can only put a named schema into the context
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      List<Schema> list0 = List.of();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Iterable<Schema>) list0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, "com.fasterxml.jackson.databind.introspect.BasicBeanDescription", (String) null, 0);
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"fixed\",\"doc\":\"com.fasterxml.jackson.databind.introspect.BasicBeanDescription\",\"size\":0}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 20);
      Schema schema1 = Schema.createFixed((String) null, "O0w'm?i /K4HNvi#lPI", "O0w'm?i /K4HNvi#lPI", 20);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertSame(schema2, schema0);
      assertTrue(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createFixed("BeDRm", "ma=", "ma=", 15);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals(Schema.Type.FIXED, schema2.getType());
      assertEquals("ma=", schema2.getDoc());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Schema schema0 = Schema.createFixed("record", "", "BeDR`", 0);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertEquals("", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Vector<Schema> vector0 = new Vector<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) vector0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      boolean boolean0 = schema1.equals(schema0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("UG8", "UG8");
      Schema[] schemaArray0 = new Schema[6];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Duplicate in union:org.apache.avro.compiler.UnresolvedSchema_549
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema[] schemaArray0 = new Schema[3];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema[] schemaArray0 = new Schema[4];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.createMap(schema1);
      Schema schema3 = Schema.applyAliases(schema2, schema1);
      assertFalse(schema3.equals((Object)schema1));
      assertNotSame(schema3, schema1);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertSame(schema0, schema1);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema0);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema0));
      assertTrue(schema3.equals((Object)schema2));
      assertFalse(schema0.equals((Object)schema2));
      assertNotSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema2));
      assertNotSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema1);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals(Schema.Type.ARRAY, schema2.getType());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("B", "B", "t%'ELH?", (List<String>) arrayList0);
      Schema schema1 = Schema.createEnum("org.apache.avro.compiler.UnresolvedSchema_557", "org.apache.avro.compiler.UnresolvedSchema_127", "org.apache.avro.compiler.UnresolvedSchema_127", (List<String>) arrayList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertEquals("org.apache.avro.compiler.UnresolvedSchema_127", schema1.getDoc());
      assertEquals("B", schema2.getDoc());
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("B", "", "t%'ELH?", (List<String>) arrayList0);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertEquals("", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("org.apache.avro.compiler.UnresolvedSchema_557", "org.apache.avro.Schema$Parser", "getMetaClass", (List<String>) linkedList0);
      boolean boolean0 = schema0.equals("getMetaClass");
      assertFalse(boolean0);
      assertEquals("org.apache.avro.Schema$Parser", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("K", "K", "org.apache.avro.compiler.UnresolvedSchema_875.XmJ", (List<String>) arrayList0);
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("WkAQ]kpCgpI\"");
        fail("Expecting exception: TracingAvroTypeException");
      
      } catch(TracingAvroTypeException e) {
         //
         // enum value 'WkAQ]kpCgpI\"' is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("XmJ", "XmJ", "org.apache.avro.compiler.UnresolvedSchema_875", (List<String>) schema_LockableArrayList0);
      boolean boolean0 = schema0.hasEnumSymbol("org.apache.avro.compiler.UnresolvedSchema_875");
      assertFalse(boolean0);
      assertEquals("XmJ", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      // Undeclared exception!
      try { 
        Schema.createEnum("axxcGd", "axxcGd", "axxcGd", (List<String>) linkedList0, "axxcGd");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // The Enum Default: axxcGd is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.add("q_");
      stack0.add("q_");
      // Undeclared exception!
      try { 
        Schema.createEnum((String) null, "com.fasterxml.jackson.core.io.NumberOutput", "com.fasterxml.jackson.core.io.NumberOutput", (List<String>) stack0, "com.fasterxml.jackson.core.io.NumberOutput");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Duplicate enum symbol: q_
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.addProp("void", "void");
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertSame(schema2, schema1);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.find("1%Wn:fo|`^2", (String) null);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertSame(schema2, schema0);
      assertEquals("unresolved schema", schema1.getDoc());
      assertFalse(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema0));
      assertSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("order", "}d1spo,K");
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertEquals("unresolved schema", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      boolean boolean0 = schema0.equals(linkedList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema0.setFields(linkedList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Fields are already set
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("order", "}d1spo,K");
      boolean boolean0 = schema0.hasFields();
      assertTrue(boolean0);
      assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Schema schema0 = Schema.createRecord((String) null, (String) null, (String) null, true);
      Schema schema1 = Schema.createMap(schema0);
      // Undeclared exception!
      try { 
        Schema.applyAliases(schema1, schema0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Schema schema0 = Schema.createRecord("SxeD", (String) null, (String) null, false);
      // Undeclared exception!
      try { 
        schema0.getField("org.apache.avro.compiler.UnresolvedSchema_621");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = schema0.getField("1(");
      assertNull(schema_Field0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LinkedList<Schema.SeenPair> linkedList0 = new LinkedList<Schema.SeenPair>();
      Schema.LockableArrayList<Schema.SeenPair> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.SeenPair>(linkedList0);
      Object object0 = schema_LockableArrayList0.clone();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, schema0);
      Schema.SeenPair schema_SeenPair1 = new Schema.SeenPair(schema_SeenPair0, schema_SeenPair0);
      boolean boolean0 = schema_SeenPair1.equals(schema_SeenPair0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LinkedList<Schema.SeenPair> linkedList0 = new LinkedList<Schema.SeenPair>();
      Schema.LockableArrayList<Schema.SeenPair> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.SeenPair>(linkedList0);
      Object object0 = schema_LockableArrayList0.clone();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, schema0);
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.addAlias((String) null);
      Set<String> set0 = schema0.getAliases();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Schema schema0 = Schema.createRecord("array", (String) null, (String) null, true);
      schema0.addAlias("array", "array");
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias("[].s");
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"fields\":[],\"aliases\":[\"[].s\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("size", (String) null);
      schema0.addAlias("size");
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"name\":\"UnresolvedSchema_553\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"size\",\"aliases\":[\"size\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      boolean boolean0 = schema_Name0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(arrayList0);
      // Undeclared exception!
      try { 
        Schema.createEnum("double", "double", "", (List<String>) schema_LockableArrayList0, "double");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Schemas may not be named after primitives: double
         //
         verifyException("org.apache.avro.Schema$NamedSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("[].s", (String) null, "[].s", (List<String>) linkedList0);
      // Undeclared exception!
      try { 
        schema0.getFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: {\"type\":\"enum\",\"name\":\"s\",\"namespace\":\"[]\",\"symbols\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createArray(schema0);
      Schema.Field schema_Field0 = new Schema.Field("fixed", schema1, "-9OY{L", linkedList0);
      boolean boolean0 = schema_Field0.equals(schema0);
      assertEquals((-1), schema_Field0.pos());
      assertEquals("-9OY{L", schema_Field0.doc());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("tmap", schema0, "tmap");
      schema_Field0.aliases();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("tmap", schema0, "tmap");
      schema_Field0.addAlias("fields");
      Set<String> set0 = schema_Field0.aliases();
      assertEquals((-1), schema_Field0.pos());
      assertTrue(set0.contains("fields"));
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = new Schema.Field("int", schema0, "int");
      schema_Field0.addAlias("hmH+)`");
      schema_Field0.addAlias("int");
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("map", schema0, "4_CvjZ`_1et:=_", object0, schema_Field_Order0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field map: null not a {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("5u,@X5vX", schema0, "5u,@X5vX", object0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Illegal initial character: 5u,@X5vX
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = new Schema.Field("int", schema0, "int");
      schema_Field0.addAlias("int");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
      ObjectMapper objectMapper0 = Schema.MAPPER;
      JsonNode jsonNode0 = objectMapper0.valueToTree((Object) stack0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("ps", schema0, "ps", jsonNode0, false, schema_Field_Order0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      schema0.hashCode();
      Schema schema1 = Schema.createArray(schema0);
      boolean boolean0 = schema0.equalCachedHash(schema1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.hashCode();
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      schema0.addProp("O", "O");
      Schema.parse("{\n  \"type\" : \"string\",\n  \"O\" : \"O\"\n}");
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        Schema.applyAliases(schema0, (Schema) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema1 = parseContext0.find("size", "size");
      schema1.addAlias("size");
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertNotSame(schema2, schema0);
      assertTrue(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.parse("{\n  \"type\" : \"string\",\n  \"O\" : \"O\"\n}");
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      schema0.addProp("O", "O");
      String string0 = schema0.toString((Collection<Schema>) linkedList0, true);
      assertEquals("{\n  \"type\" : \"string\",\n  \"O\" : \"O\"\n}", string0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      String string0 = schema0.toString((Collection<Schema>) null, true);
      assertEquals("{\n  \"type\" : \"record\",\n  \"fields\" : [ ]\n}", string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.UNION;
      // Undeclared exception!
      try { 
        Schema.create(schema_Type0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't create a: UNION
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FIXED;
      String string0 = schema_Type0.getName();
      assertEquals("fixed", string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ValueNode valueNode0 = jsonNodeFactory0.pojoNode(schema0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ValueNode valueNode0 = jsonNodeFactory0.pojoNode(schema0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      NumericNode numericNode0 = jsonNodeFactory0.numberNode(2305L);
      boolean boolean0 = schema0.isValidDefault(numericNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ValueNode valueNode0 = jsonNodeFactory0.pojoNode(schema_Type0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Schema schema0 = Schema.parse("{\n  \"type\" : \"array\",\n  \"items\" : [ ]\n}");
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      schema1.hashCode();
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 20);
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 20);
      int int0 = schema0.getFixedSize();
      assertEquals(20, int0);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 20);
      Schema schema1 = Schema.createFixed("FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS", "O0w'm?i /K4HNvi#lPI", "O0w'm?i /K4HNvi#lPI", 20);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertEquals("O0w'm?i /K4HNvi#lPI", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.addAlias((String) null);
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"fields\":[],\"aliases\":[null]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.resolve(schema0);
      assertTrue(schema1.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(">+rMF9C[#=@~bCo; JP", linkedList0);
      boolean boolean0 = schema_SeenPair0.equals(">+rMF9C[#=@~bCo; JP");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  @org.junit.Ignore("Filtered: brittle EvoSuite assertion on Schema JSON string with custom property")
  public void test097()  throws Throwable  {
    // Filtered: brittle EvoSuite assertion on Schema JSON serialization with custom properties.
    return;
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Integer integer0 = schema0.getIndexNamed("items");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addProp("(enabled=0x%x,disabled=0x%x)", "(enabled=0x%x,disabled=0x%x)");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't set properties on a union: [\"string\"]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("org.apache.avro.compiler.UnresolvedSchema_144");
      String string0 = schema_Names0.space();
      assertEquals("org.apache.avro.compiler.UnresolvedSchema_144", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.space("6jvn%'cOD");
      assertEquals("6jvn%'cOD", schema_Names0.space());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("ordAer", "}d1spo,K");
      Schema.Names schema_Names0 = new Schema.Names("ordAer");
      schema_Names0.add(schema0);
      assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("B", "*?iQU!mFo'B*", "org.apache.avro.Schema$StringSchema", (List<String>) arrayList0);
      schema0.getEnumSymbols();
      assertEquals("*?iQU!mFo'B*", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("B", "B", "t%'ELH?", (List<String>) arrayList0);
      schema0.hashCode();
      assertEquals("B", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ValueNode valueNode0 = jsonNodeFactory0.pojoNode(schema_Parser0);
      // Undeclared exception!
      try { 
        Schema.parse((JsonNode) valueNode0, parseContext0, (String) null);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Schema not yet supported: {\"validateDefaults\":true,\"types\":{}}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parseInternal("record");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'record': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      schema_Parser0.setValidateDefaults(true);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("CAN_WRITE_BINARY_NATIVELY", schema0, "CAN_WRITE_BINARY_NATIVELY", "<*<!_(q1\"|", schema_Field_Order0);
      stack0.add(schema_Field0);
      Schema.Field schema_Field1 = new Schema.Field("CAN_WRITE_BINARY_NATIVELY", schema0, "CAN_WRITE_BINARY_NATIVELY", "CAN_WRITE_BINARY_NATIVELY");
      stack0.addElement(schema_Field1);
      // Undeclared exception!
      try { 
        Schema.createRecord((List<Schema.Field>) stack0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Duplicate field CAN_WRITE_BINARY_NATIVELY in record null: CAN_WRITE_BINARY_NATIVELY type:UNION pos:1 and CAN_WRITE_BINARY_NATIVELY type:UNION pos:0.
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Locale locale0 = Locale.CHINESE;
      Set<String> set0 = locale0.getUnicodeLocaleKeys();
      // Undeclared exception!
      try { 
        schema0.fieldsToJson(set0, "7V70:1{QwrN-", (JsonGenerator) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema0.hasEnumSymbol("Qk{s0?[KEX8e");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      // Undeclared exception!
      try { 
        schema0.setFields(arrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      File file0 = new File("FIXED");
      try { 
        Schema.parse(file0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // FIXED (No such file or directory)
         //
         verifyException("java.io.FileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("", "");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      boolean boolean0 = Schema.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getFixedSize();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not fixed: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  @org.junit.Ignore("Filtered: brittle EvoSuite assertion on Schema JSON string with custom property")
  public void test116()  throws Throwable  {
    // Filtered: brittle EvoSuite assertion on Schema JSON serialization with custom properties.
    return;
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumDefault();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("com.fasterml.jackson.databind.ser.impl.StringArraySerializer");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      String string0 = schema0.getDoc();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getElementType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an array: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getNamespace();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 20);
      // Undeclared exception!
      try { 
        schema0.hasFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: {\"type\":\"fixed\",\"size\":20}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      InputStream inputStream0 = InputStream.nullInputStream();
      // Undeclared exception!
      try { 
        Schema.parse(inputStream0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a map: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      // Undeclared exception!
      try { 
        schema0.getTypes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$MapSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema0.getIndexNamed((String) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getAliases();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "name";
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(stringArray0);
      Schema schema0 = Schema.createEnum("name", "name", "name", (List<String>) schema_LockableArrayList0, "name");
      // Undeclared exception!
      try { 
        schema0.getField("org.apache.avro.Schema$Field$Order");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: {\"type\":\"enum\",\"name\":\"name\",\"namespace\":\"name\",\"doc\":\"name\",\"symbols\":[\"name\"],\"default\":\"name\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Schema.setValidateDefaults(false);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      LogicalType logicalType0 = new LogicalType("Z,eKCm");
      Schema schema1 = logicalType0.addToSchema(schema0);
      assertSame(schema0, schema1);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Schema schema0 = Schema.createRecord("withDefaultImpl", "^3d|p}sV", "uIH#gXGta[BiS{q&Re", true);
      schema0.writeReplace();
      assertEquals("^3d|p}sV", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      HashSet<String> hashSet0 = new HashSet<String>();
      String string0 = schema0.toString((Set<String>) hashSet0, true);
      assertTrue(hashSet0.isEmpty());
      assertEquals("{\n  \"type\" : \"record\",\n  \"fields\" : [ ]\n}", string0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.isError();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("[]5.s");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Schema schema0 = Schema.createFixed("record", "", "BeDR`", 0);
      Schema.Field schema_Field0 = new Schema.Field("record", schema0, "", "AnnotationIntrospector.");
      int int0 = schema_Field0.pos();
      assertEquals("", schema0.getDoc());
      assertEquals("", schema_Field0.doc());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("map", schema0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertFalse(boolean0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("tmap", schema0, "tmap");
      schema_Field0.defaultVal();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("logicalType", schema0, "logicalType", (Object) null);
      schema_Field0.doc();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("CAN_WRITE_BINARY_NATIVELY", schema0, "CAN_WRITE_BINARY_NATIVELY", "<*<!_(q1\"|", schema_Field_Order0);
      stack0.add(schema_Field0);
      stack0.addElement(schema_Field0);
      // Undeclared exception!
      try { 
        Schema.createRecord((List<Schema.Field>) stack0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Field already used: CAN_WRITE_BINARY_NATIVELY type:UNION pos:0
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = new Schema.Field("B", schema0, "Zfh+bgOm;8w|:4c)qyk");
      schema_Field0.defaultValue();
      assertEquals("Zfh+bgOm;8w|:4c)qyk", schema_Field0.doc());
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = new Schema.Field("int", schema0, "int");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertEquals((-1), schema_Field1.pos());
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("START_ARRAY", schema0, "START_ARRAY", "START_ARRAY");
      schema_Field0.schema();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("START_ARRAY", schema0, "START_ARRAY", "START_ARRAY");
      schema_Field0.order();
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(0);
      Charset charset0 = Charset.defaultCharset();
      Set<String> set0 = charset0.aliases();
      boolean boolean0 = schema_LockableArrayList0.addAll(0, (Collection<? extends String>) set0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>(4);
      boolean boolean0 = schema_LockableArrayList0.addAll((Collection<?>) schema_LockableArrayList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("XmJ", "XmJ", "org.apache.avro.compiler.UnresolvedSchema_875", (List<String>) schema_LockableArrayList0);
      schema_LockableArrayList0.remove((Object) schema0);
      assertEquals("XmJ", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>(0);
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.remove((-74));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      TreeSet<String> treeSet0 = new TreeSet<String>();
      boolean boolean0 = schema_LockableArrayList0.removeAll(treeSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>(0);
      Schema.LockableArrayList<Schema> schema_LockableArrayList1 = new Schema.LockableArrayList<Schema>(0);
      boolean boolean0 = schema_LockableArrayList1.retainAll(schema_LockableArrayList0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      schema_LockableArrayList0.clear();
      assertTrue(schema_LockableArrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      schema1.hashCode();
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Schema schema0 = Schema.parse("{\"type\":\"map\",\"values\":[\"string\"]}", true);
      assertNull(schema0.getDoc());
  }
}
