/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 12:10:35 CEST 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.PropertyAccessor;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.util.ByteArrayBuilder;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.NumericNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.ValueNode;
import java.io.File;
import java.io.InputStream;
import java.io.OutputStream;
import java.lang.reflect.Array;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.avro.AvroRuntimeException;
import org.apache.avro.AvroTypeException;
import org.apache.avro.LogicalType;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.SchemaParseException;
import org.apache.avro.path.TracingAvroTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(resetStaticState = false, separateClassLoader = false) 
public class Schema_C2_ESTest extends Schema_C2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("YTES", schema0);
      boolean boolean0 = schema_Field0.equals("YTES");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      LogicalType logicalType0 = new LogicalType("isRecord");
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = logicalType0.addToSchema(schema0);
      // Undeclared exception!
      try { 
        schema1.getValueType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a map: {\"type\":\"null\",\"logicalType\":\"isRecord\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(false);
      NumericNode numericNode0 = jsonNodeFactory0.numberNode((-1968526675));
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("WRAP_EXCEPTIONS", schema0, "GWp+/vH]C?0~^3-V3", numericNode0, false, schema_Field_Order0);
      arrayList0.add(schema_Field0);
      assertEquals("GWp+/vH]C?0~^3-V3", schema_Field0.doc());
      
      Schema schema1 = Schema.createRecord((List<Schema.Field>) arrayList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertSame(schema2, schema0);
      assertFalse(schema2.equals((Object)schema1));
      assertTrue(schema2.isUnion());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema1 = Schema.createRecord((List<Schema.Field>) arrayList0);
      schema1.addAlias("WRAP_EXCEPTIONS");
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertNotSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parse("{\"type\":\"record\",\"name\":\"UnresolvedSchema_1642\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"C0?PU2()dqQ0E.C0?PU2()dqQ0E\",\"aliases\":[\"u'_z.0o2S;62<)tjceG.INT\"]}");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Undefined schema: C0?PU2()dqQ0E.C0?PU2()dqQ0E
         //
         verifyException("org.apache.avro.util.SchemaResolver$ResolvingVisitor", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      Schema schema0 = schema_Parser0.parseInternal("{\"type\":\"map\",\"values\":[\"string\"]}");
      assertEquals(Schema.Type.MAP, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      // Undeclared exception!
      try { 
        schema_Parser0.parse("{\"type\":\"enum\",\"symbols\":[]}");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // No name in schema: {\"type\":\"enum\",\"symbols\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"error\",\"doc\":\"o#!8H<K>,-P9t\"}");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // No name in schema: {\"type\":\"error\",\"doc\":\"o#!8H<K>,-P9t\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      schema_Parser0.parse("[\"string\"]");
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      Schema schema1 = Schema.createMap(schema0);
      boolean boolean0 = schema1.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Byte byte0 = Byte.valueOf((byte) (-26));
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(byte0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema schema0 = Schema.createMap((Schema) null);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      NumericNode numericNode0 = jsonNodeFactory0.numberNode((short)14);
      boolean boolean0 = schema1.isValidDefault(numericNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Schema schema0 = Schema.createFixed("doc", "doc", "doc", 2);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0, (String) null);
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(false);
      Float float0 = new Float(0.0F);
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(float0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      NumericNode numericNode0 = jsonNodeFactory0.numberNode((short) (-13039));
      Schema schema0 = parseContext0.find("boolean", "boolean");
      boolean boolean0 = schema0.isValidDefault(numericNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Byte byte0 = Byte.valueOf((byte) (-117));
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(byte0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Byte byte0 = Byte.valueOf((byte) (-110));
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(byte0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("]1C=~pY kc'*RZGm", "]1C=~pY kc'*RZGm");
      boolean boolean0 = schema0.isValidDefault((JsonNode) null);
      assertFalse(boolean0);
      assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("BYTES", schema0, "BYTES", "BYTES", schema_Field_Order0);
      assertEquals((-1), schema_Field0.pos());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.put((Schema.Name) null, (Schema) null);
      Schema schema0 = schema_Names0.put((Schema.Name) null, (Schema) null);
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      Schema.Names schema_Names0 = new Schema.Names("[\"string\"]");
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      schema_Names0.put(schema_Name0, schema0);
      boolean boolean0 = schema_Names0.contains(schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      Schema.Names schema_Names0 = new Schema.Names((String) null);
      boolean boolean0 = schema_Names0.contains(schema0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Names schema_Names0 = new Schema.Names("double");
      Schema.Name schema_Name0 = new Schema.Name("doc", "double");
      schema_Names0.put(schema_Name0, schema0);
      Schema schema1 = schema_Names0.get("doc");
      assertEquals(Schema.Type.UNION, schema1.getType());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("&6d_$pm", true);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unexpected character ('&' (code 38)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"record\",\"name\":\"UnresolvedSchema_1632\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"C0?PU2()dqQ0E.U4cQ9:Z2iK4X\\4R3\"}", false);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized character escape '4' (code 52)
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 193]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("{\"type\":\"array\",\"items\":[\"string\"]}", stringArray0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // dangling content after end of schema: nullnullnullnull
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, "w4:UVB-SQJ!", 2);
      String string0 = schema0.toString();
      assertEquals("{\"type\":\"fixed\",\"size\":2}", string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Schema schema0 = Schema.createFixed("doc", "doc", "doc", 2);
      String string0 = schema0.toString();
      assertEquals("{\"type\":\"fixed\",\"name\":\"doc\",\"namespace\":\"doc\",\"doc\":\"doc\",\"size\":2}", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Schema schema0 = Schema.createFixed("doc", "doc", "doc", 2);
      boolean boolean0 = schema0.equals("doc");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Schema schema0 = Schema.createFixed("doc", "doc", "doc", 2);
      Schema.Parser schema_Parser0 = new Schema.Parser();
      Schema[] schemaArray0 = new Schema[6];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      schemaArray0[2] = schema0;
      schemaArray0[3] = schema0;
      schemaArray0[4] = schema0;
      schemaArray0[5] = schema0;
      List<Schema> list0 = List.of(schemaArray0);
      assertTrue(list0.contains(schema0));
      
      schema_Parser0.addTypes((Iterable<Schema>) list0);
      Schema schema1 = schema_Parser0.parseInternal("{\"type\":\"fixed\",\"name\":\"doc\",\"namespace\":\"doc\",\"doc\":\"doc\",\"size\":2}");
      assertNotSame(schema1, schema0);
      assertEquals(Schema.Type.FIXED, schema1.getType());
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertSame(schema0, schema1);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0, "UNION");
      Schema schema1 = Schema.createArray(schema0);
      Schema[] schemaArray0 = new Schema[4];
      schemaArray0[0] = schema1;
      schemaArray0[1] = schema1;
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
      // Undeclared exception!
      try { 
        Schema.createUnion((List<Schema>) schema_LockableArrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Duplicate in union:array
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Schema[] schemaArray0 = new Schema[4];
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema[] schemaArray0 = new Schema[4];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Schema schema0 = Schema.createFixed("doc", "doc", "doc", 2);
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.createMap(schema1);
      Schema schema3 = Schema.applyAliases(schema2, schema1);
      assertFalse(schema3.equals((Object)schema1));
      assertNotSame(schema3, schema1);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema2 = parseContext0.resolve(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertTrue(schema3.equals((Object)schema2));
      assertFalse(schema3.equals((Object)schema0));
      assertFalse(schema0.equals((Object)schema1));
      assertSame(schema3, schema1);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema2 = parseContext0.resolve(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema0.equals((Object)schema2));
      assertTrue(schema3.equals((Object)schema2));
      assertFalse(schema3.equals((Object)schema0));
      assertNotSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema1);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0, "UNION");
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.isUnion());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum((String) null, "boolean", "Empty name", (List<String>) vector0, (String) null);
      // Undeclared exception!
      try { 
        schema0.hasFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: {\"type\":\"enum\",\"doc\":\"boolean\",\"symbols\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) vector0, (String) null);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertFalse(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Vector<String> vector0 = new Vector<String>();
      Schema schema1 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) vector0, (String) null);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals(Schema.Type.ENUM, schema2.getType());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) vector0, (String) null);
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal((String) null);
        fail("Expecting exception: TracingAvroTypeException");
      
      } catch(TracingAvroTypeException e) {
         //
         // enum value 'null' is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0, (String) null);
      boolean boolean0 = schema0.hasEnumSymbol((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      // Undeclared exception!
      try { 
        Schema.createEnum((String) null, "", "", (List<String>) arrayList0, "s");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // The Enum Default: s is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "values";
      stringArray0[1] = "values";
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(stringArray0);
      // Undeclared exception!
      try { 
        Schema.createEnum("values", "values", "values", (List<String>) schema_LockableArrayList0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Duplicate enum symbol: values
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      vector0.add("FLOAT");
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) vector0, (String) null);
      // Undeclared exception!
      try { 
        schema0.getFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: {\"type\":\"enum\",\"symbols\":[\"FLOAT\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Schema schema0 = Schema.createRecord("alues", "alues", "alues", true);
      // Undeclared exception!
      try { 
        schema0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("", "");
      schema0.hashCode();
      assertEquals("unresolved schema", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("C0?PU2()dqQ0E", "C0?PU2()dqQ0E");
      Schema schema1 = parseContext0.find("{\"type\":\"record\",\"name\":\"UnresolvedSchema_1639\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"C0?PU2()dqQ0E.C0?PU2()dqQ0E\",\"aliases\":[\"C0?PU2()dqQ0E.INT\"]}", "INT");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertSame(schema2, schema1);
      assertFalse(schema2.equals((Object)schema0));
      assertEquals("unresolved schema", schema2.getDoc());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      ArrayList<Schema> arrayList0 = new ArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) arrayList0);
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema1 = parseContext0.find("[nf)ZgLe#x|HW?J1n", "1. bYc0nf+L^<");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals("unresolved schema", schema2.getDoc());
      assertSame(schema2, schema1);
      assertFalse(schema2.isUnion());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("", "");
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertEquals("unresolved schema", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      // Undeclared exception!
      try { 
        schema0.setFields(arrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Fields are already set
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      boolean boolean0 = schema0.hasFields();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema schema1 = parseContext0.resolve(schema0);
      assertTrue(schema1.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema schema0 = Schema.createRecord("dJoc.dJoc", "dJoc.dJoc", (String) null, true);
      // Undeclared exception!
      try { 
        schema0.isValidDefault(objectNode0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Schema schema0 = Schema.createRecord("org.apache.avro.compiler.UnresolvedSchema_14", (String) null, "org.apache.avro.compiler.UnresolvedSchema_14", false);
      // Undeclared exception!
      try { 
        schema0.getField((String) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = schema0.getField(", ");
      assertNull(schema_Field0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      Schema.SeenPair schema_SeenPair1 = new Schema.SeenPair(schema_SeenPair0, object0);
      boolean boolean0 = schema_SeenPair1.equals(schema_SeenPair0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair("`]4W{C~H", "`]4W{C~H");
      boolean boolean0 = schema_SeenPair0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(object0, object0);
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias("jZ", "jZ");
      Set<String> set0 = schema0.getAliases();
      assertFalse(set0.contains("jZ"));
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("C0?PU2()dqQ0E", "C0?PU2()dqQ0E");
      schema0.addAlias("INT", "C0?PU2()dqQ0E");
      // Undeclared exception!
      try { 
        schema0.addAlias("", "");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Empty name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      String[] stringArray0 = new String[1];
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(stringArray0);
      // Undeclared exception!
      try { 
        Schema.createEnum("bytes", "bytes", (String) null, (List<String>) schema_LockableArrayList0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Schemas may not be named after primitives: bytes
         //
         verifyException("org.apache.avro.Schema$NamedSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      String string0 = schema_Name0.getQualified((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name("BYTES", "BYTES");
      String string0 = schema_Name0.getQualified("BYTES");
      assertEquals("BYTES.BYTES", schema_Name0.toString());
      assertEquals("BYTES", string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      ParseContext parseContext0 = new ParseContext();
      Schema.Name schema_Name0 = new Schema.Name("BYTES", "BYTES");
      Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0, "UNION");
      schema_Name0.equals(schema0);
      assertEquals("BYTES.BYTES", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name("java.sql.Date", "flrOoat");
      boolean boolean0 = schema_Name0.equals(schema_Name0);
      assertEquals("java.sql.Date", schema_Name0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema schema0 = schema_Names0.get("default");
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("LONG", schema0, "LONG");
      schema_Field0.addAlias("LONG");
      Set<String> set0 = schema_Field0.aliases();
      assertTrue(set0.contains("LONG"));
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("USE_WRAPPER_NAME_AS_PROPERTY_NAME", schema0);
      schema_Field0.addAlias("USE_WRAPPER_NAME_AS_PROPERTY_NAME");
      schema_Field0.addAlias("USE_WRAPPER_NAME_AS_PROPERTY_NAME");
      assertEquals("USE_WRAPPER_NAME_AS_PROPERTY_NAME", schema_Field0.name());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("YTES", schema0);
      schema_Field0.addAlias("ING6");
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("fixed", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      boolean boolean0 = schema0.isNullable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Stack<Schema> stack0 = new Stack<Schema>();
      Schema schema1 = Schema.createUnion((List<Schema>) stack0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      schema0.hashCode();
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.resolve(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema0));
      assertSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Parser schema_Parser0 = new Schema.Parser();
      Schema schema1 = schema_Parser0.parse("[\"string\"]");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema0));
      assertTrue(schema_Parser0.getValidateDefaults());
      assertNotSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("C0?PU2()dqQ0E", "C0?PU2()dqQ0E");
      schema0.addAlias("INT", "C0?PU2()dqQ0E");
      Schema schema1 = Protocol.SYSTEM_ERROR;
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals("unresolved schema", schema0.getDoc());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      String string0 = schema0.toString((Collection<Schema>) null, true);
      assertEquals("\"string\"", string0);
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.ARRAY;
      // Undeclared exception!
      try { 
        Schema.create(schema_Type0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't create a: ARRAY
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      String string0 = schema_Type0.getName();
      assertEquals("long", string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Byte byte0 = Byte.valueOf((byte)6);
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(byte0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.equals(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertSame(schema2, schema0);
      assertFalse(schema2.equals((Object)schema1));
      assertTrue(schema2.isUnion());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      // Undeclared exception!
      try { 
        schema0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$ArraySchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      schema_LockableArrayList0.add(schema0);
      String string0 = schema0.toString((Collection<Schema>) schema_LockableArrayList0, false);
      assertEquals("[]", string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Integer integer0 = schema0.getIndexNamed("SU)fk!qK)y5gmhdM");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addProp("fields", "fields");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't set properties on a union: [\"string\"]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("org.apache.avro.compiler.UnresolvedSchema_38");
      String string0 = schema_Names0.space();
      assertEquals("org.apache.avro.compiler.UnresolvedSchema_38", string0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("org.apache.avro.compiler.UnresolvedSchema_41");
      schema_Names0.space("M/h]");
      assertTrue(schema_Names0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.add(schema0);
      assertNull(schema_Names0.space());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) vector0, (String) null);
      List<String> list0 = schema0.getEnumSymbols();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      // Undeclared exception!
      try { 
        schema_Parser0.parseInternal("null");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Schema not yet supported: null
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      schema_Parser0.setValidateDefaults(true);
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      schema_Parser0.getTypes();
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      ParseContext parseContext0 = new ParseContext();
      Schema.Name schema_Name0 = new Schema.Name("BYTES", "BYTES");
      Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0, "UNION");
      Schema schema1 = Schema.createArray(schema0);
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.put(schema_Name0, schema0);
      // Undeclared exception!
      try { 
        schema_Names0.put(schema_Name0, schema1);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Can't redefine: BYTES.BYTES
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Locale.IsoCountryCode locale_IsoCountryCode0 = Locale.IsoCountryCode.PART1_ALPHA2;
      Set<String> set0 = Locale.getISOCountries(locale_IsoCountryCode0);
      JsonFactory jsonFactory0 = new JsonFactory();
      ByteArrayBuilder byteArrayBuilder0 = new ByteArrayBuilder();
      JsonGenerator jsonGenerator0 = jsonFactory0.createGenerator((OutputStream) byteArrayBuilder0);
      // Undeclared exception!
      try { 
        schema0.fieldsToJson(set0, "org.apache.avro.compiler.UnresolvedSchema_151", jsonGenerator0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: []
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0, (String) null);
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.hasEnumSymbol((String) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      // Undeclared exception!
      try { 
        schema0.setFields(arrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(true);
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0, "UNION");
      // Undeclared exception!
      try { 
        schema0.addAlias("UNION", "logicalType");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: []
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      boolean boolean0 = Schema.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getFixedSize();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not fixed: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Protocol protocol0 = new Protocol("", "7&\"F,>");
      // Undeclared exception!
      try { 
        protocol0.SYSTEM_ERROR.getEnumDefault();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Schema schema0 = Schema.createFixed("doc", "doc", "doc", 2);
      int int0 = schema0.computeHash();
      //  // Unstable assertion: assertEquals((-1849833968), int0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("[ \"string\" ]");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      String string0 = schema0.getDoc();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.get("float");
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getNamespace();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse((InputStream) null);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parseJsonToObject("y");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'y': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      // Undeclared exception!
      try { 
        schema1.getTypes();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: {\"type\":\"array\",\"items\":[\"string\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      Schema schema0 = Schema.createRecord("jZ", "jZ", "ARRAY", true);
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"error\",\"name\":\"jZ\",\"namespace\":\"ARRAY\",\"doc\":\"jZ\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("]1C=~pY kc'*RZGm", "]1C=~pY kc'*RZGm");
      // Undeclared exception!
      try { 
        schema0.getIndexNamed("]1C=~pY kc'*RZGm");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: {\"type\":\"record\",\"name\":\"UnresolvedSchema_821\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"]1C=~pY kc'*RZGm.]1C=~pY kc'*RZGm\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getAliases();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      // Undeclared exception!
      try { 
        schema0.getField("org.apache.avro.compiler.UnresolvedSchema_29");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$ArraySchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Schema.setValidateDefaults(false);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Object object0 = schema0.writeReplace();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.isError();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) arrayList0);
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("|");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = Schema.parse((JsonNode) arrayNode0, parseContext0, "org.apache.avro.compiler.UnresolvedSchema_91");
      Schema.Field schema_Field0 = new Schema.Field("long", schema0);
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("LONG", schema0);
      Object object0 = schema_Field0.defaultVal();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("LONG", schema0, "LONG");
      List<Schema.Field> list0 = List.of(schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0, schema_Field0);
      // Undeclared exception!
      try { 
        Schema.createRecord(list0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Field already used: LONG type:UNION pos:0
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(false);
      Random random0 = new Random(9);
      BigInteger bigInteger0 = BigInteger.probablePrime(9, random0);
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(bigInteger0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("string", schema0, "|^x5l^]h)-@", valueNode0, false, schema_Field_Order0);
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>(9);
      schema_LockableArrayList0.add(schema_Field0);
      assertEquals((-1), schema_Field0.pos());
      
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      String string0 = schema1.toString();
      assertEquals("{\"type\":\"record\",\"fields\":[{\"name\":\"string\",\"type\":\"string\",\"doc\":\"|^x5l^]h)-@\",\"default\":281}]}", string0);
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.addAll(3, (Collection<? extends Schema.Field>) vector0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 3, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.addAll((Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>(objectArray0);
      boolean boolean0 = schema_LockableArrayList0.remove((Object) "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Schema.LockableArrayList<JsonInclude.Include> schema_LockableArrayList0 = new Schema.LockableArrayList<JsonInclude.Include>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.remove((-2671));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      HashMap<String, PropertyAccessor>[] hashMapArray0 = (HashMap<String, PropertyAccessor>[]) Array.newInstance(HashMap.class, 9);
      Schema.LockableArrayList<HashMap<String, PropertyAccessor>> schema_LockableArrayList0 = new Schema.LockableArrayList<HashMap<String, PropertyAccessor>>(hashMapArray0);
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.removeAll((Collection<?>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema.LockableArrayList<Object> schema_LockableArrayList1 = new Schema.LockableArrayList<Object>(114);
      boolean boolean0 = schema_LockableArrayList0.retainAll(schema_LockableArrayList1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      LinkedList<Object> linkedList0 = new LinkedList<Object>();
      Schema.LockableArrayList<Object> schema_LockableArrayList0 = new Schema.LockableArrayList<Object>(linkedList0);
      schema_LockableArrayList0.clear();
      assertTrue(schema_LockableArrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema.Field schema_Field0 = new Schema.Field("items", schema0, "items");
      schema_LockableArrayList0.add(schema_Field0);
      assertEquals((-1), schema_Field0.pos());
      
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      String string0 = schema1.toString();
      assertEquals("{\"type\":\"record\",\"fields\":[{\"name\":\"items\",\"type\":[\"string\"],\"doc\":\"items\"}]}", string0);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      schema1.hashCode();
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("C0?PU2()dqQ0E", "C0?PU2()dqQ0E");
      schema0.addAlias("INT", "C0?PU2()dqQ0E");
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals("unresolved schema", schema0.getDoc());
      assertFalse(schema2.equals((Object)schema0));
      assertSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      String string0 = schema1.toString();
      assertEquals("{\"type\":\"map\",\"values\":[\"string\"]}", string0);
  }
}
