/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 11:45:51 CEST 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerationException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.cfg.CoercionAction;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.databind.node.ValueNode;
import java.io.ByteArrayInputStream;
import java.io.DataOutput;
import java.io.DataOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.Stack;
import java.util.TreeSet;
import org.apache.avro.AvroRuntimeException;
import org.apache.avro.AvroTypeException;
import org.apache.avro.LogicalType;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.SchemaParseException;
import org.apache.avro.path.TracingAvroTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(resetStaticState = false, separateClassLoader = false) 
public class Schema_C3_ESTest extends Schema_C3_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      boolean boolean0 = true;
      Schema schema0 = Schema.createRecord("lenient", "lenient", "lenient", true);
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(boolean0);
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      // Undeclared exception!
      try { 
        schema0.isValidDefault(objectNode0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("long", "long");
      Schema.Names schema_Names0 = new Schema.Names();
      // Undeclared exception!
      try { 
        schema_Names0.add(schema0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.apache.avro.Schema$LongSchema cannot be cast to class org.apache.avro.Schema$NamedSchema (org.apache.avro.Schema$LongSchema and org.apache.avro.Schema$NamedSchema are in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @12f45553)
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Schema.LockableArrayList<CoercionAction> schema_LockableArrayList0 = new Schema.LockableArrayList<CoercionAction>();
      schema_LockableArrayList0.clear();
      assertTrue(schema_LockableArrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      // Undeclared exception!
      try { 
        Schema.applyAliases(schema0, (Schema) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      schema0.addProp("6/Z;}`", (Object) "6/Z;}`");
      // Undeclared exception!
      try { 
        schema0.getEnumDefault();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"string\",\"6/Z;}`\":\"6/Z;}`\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parseJson("5xK8");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unexpected character ('x' (code 120)): Expected space separating root-level values
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Schema.LockableArrayList<CoercionAction> schema_LockableArrayList0 = new Schema.LockableArrayList<CoercionAction>();
      CoercionAction coercionAction0 = CoercionAction.AsEmpty;
      schema_LockableArrayList0.lock();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.add(coercionAction0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$LockableArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord("oo", "type", "7l5D'6u(tJN", true, (List<Schema.Field>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("oo", schema0, "7l5D'6u(tJN");
      linkedList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertSame(schema2, schema0);
      assertEquals("type", schema2.getDoc());
      assertFalse(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"record\",\"fields\":[]}", false);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // No name in schema: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parse("null");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Schema not yet supported: null
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      schema_Parser0.parseInternal("{\n  \"type\" : \"map\",\n  \"values\" : {\n    \"type\" : \"fixed\",\n    \"name\" : \"P\",\n    \"namespace\" : \"P\",\n    \"doc\" : \"P\",\n    \"size\" : 22\n  }\n}");
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Schema schema0 = Schema.createRecord("P", "P", "P", true);
      ArrayList<Schema> arrayList0 = new ArrayList<Schema>();
      boolean boolean0 = true;
      String string0 = schema0.toString((Collection<Schema>) arrayList0, boolean0);
      Schema.Parser schema_Parser0 = new Schema.Parser();
      // Undeclared exception!
      try { 
        schema_Parser0.parseInternal(string0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Record has no fields: {\"type\":\"error\",\"name\":\"P\",\"namespace\":\"P\",\"doc\":\"P\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      schema_Parser0.parseInternal("{\n  \"type\" : \"record\",\n  \"name\" : \"UnresolvedSchema_815\",\n  \"namespace\" : \"org.apache.avro.compiler\",\n  \"doc\" : \"unresolved schema\",\n  \"fields\" : [ ],\n  \"org.apache.avro.idl.unresolved.name\" : \"org.apache.avro.Schema$StringSchema\"\n}");
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Schema schema0 = Schema.parse("\"string\"", false);
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("long", "long");
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Schema schema0 = Schema.createArray((Schema) null);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
      Schema schema0 = Schema.create(schema_Type0);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("long", "long");
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Byte byte0 = new Byte((byte)12);
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(byte0);
      boolean boolean0 = schema0.isValidDefault(valueNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      boolean boolean0 = schema0.isValidDefault((JsonNode) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      schema_Names0.put(schema_Name0, schema0);
      Schema schema1 = schema_Names0.put(schema_Name0, schema0);
      assertSame(schema1, schema0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
      Schema.Names schema_Names0 = new Schema.Names();
      boolean boolean0 = schema_Names0.contains(schema0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Names schema_Names0 = new Schema.Names();
      Schema.Name schema_Name0 = new Schema.Name("F4y\"9|Y5O3X`,n.o3", (String) null);
      schema_Names0.put(schema_Name0, schema0);
      Schema schema1 = schema_Names0.get("F4y\"9|Y5O3X`,n.o3");
      assertNull(schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Schema schema0 = Schema.parse("\"string\"", true);
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) linkedList0);
      List<Schema> list0 = List.of(schema0, schema0, schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      TreeSet<Schema> treeSet0 = new TreeSet<Schema>();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Iterable<Schema>) treeSet0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, "HUu@j&7*^X8$bBIe", 1757);
      // Undeclared exception!
      try { 
        schema0.getEnumDefault();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"fixed\",\"size\":1757}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "P", "P", 7);
      schema0.addProp("P.P", (Object) "P.P");
      Schema schema1 = Schema.createFixed("P", "P", "P", 7);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "P", "P", 7);
      Schema schema1 = Schema.createFixed("P", "P", "P", 7);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertTrue(schema2.equals((Object)schema1));
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "NULL", "NULL", 7);
      boolean boolean0 = schema0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals("NULL", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "P", "P", 7);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertEquals("P", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "P", "P", 7);
      Schema schema1 = Schema.createFixed("P", "{\n  \"type\" : \"map\",\n  \"values\" : {\n    \"type\" : \"fixed\",\n    \"name\" : \"P\",\n    \"namespace\" : \"P\",\n    \"doc\" : \"P\",\n    \"size\" : 7\n  }\n}", "%", 7);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals("{\n  \"type\" : \"map\",\n  \"values\" : {\n    \"type\" : \"fixed\",\n    \"name\" : \"P\",\n    \"namespace\" : \"P\",\n    \"doc\" : \"P\",\n    \"size\" : 7\n  }\n}", schema2.getDoc());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Names schema_Names0 = new Schema.Names();
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.resolve(schema0);
      Schema schema2 = schema_Names0.getOrDefault((Object) null, schema1);
      boolean boolean0 = schema0.equals(schema2);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      List<Schema> list0 = parseContext0.resolveAllSchemas();
      Schema schema0 = Schema.createUnion(list0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertTrue(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      List<Schema> list0 = List.of(schema0, schema0, schema0, schema0);
      // Undeclared exception!
      try { 
        Schema.createUnion(list0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Duplicate in union:map
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema[] schemaArray0 = new Schema[1];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Nameless in union:[{\"type\":\"record\",\"fields\":[]}]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.createMap(schema0);
      Schema schema3 = Schema.applyAliases(schema2, schema1);
      assertTrue(schema3.equals((Object)schema1));
      assertNotSame(schema3, schema1);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.createMap(schema1);
      Schema schema3 = Schema.applyAliases(schema2, schema1);
      assertFalse(schema3.equals((Object)schema1));
      assertSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertSame(schema1, schema0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema0);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema0));
      assertTrue(schema3.equals((Object)schema2));
      assertNotSame(schema3, schema2);
      assertFalse(schema0.equals((Object)schema2));
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema1);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema2));
      assertNotSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("com.fasterxml.jackson.core.base.GeneratorBase", (String) null, "com.fasterxml.jackson.core.base.GeneratorBase", (List<String>) schema_LockableArrayList0);
      Schema schema1 = Schema.createMap(schema0);
      // Undeclared exception!
      try { 
        schema1.getEnumOrdinal((String) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"map\",\"values\":{\"type\":\"enum\",\"name\":\"GeneratorBase\",\"namespace\":\"com.fasterxml.jackson.core.base\",\"symbols\":[]}}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("fY", "fY", "fY", (List<String>) schema_LockableArrayList0);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertFalse(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("nfY", "nfY", "com.faster'ml.jakson.datbinf.node.IntNode.Unresolved/chema", (List<String>) schema_LockableArrayList0);
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertEquals(Schema.Type.ENUM, schema2.getType());
      assertEquals("nfY", schema2.getDoc());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("nfY", "nfY", "nfY", (List<String>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("a+ROF;z?H80_v");
        fail("Expecting exception: TracingAvroTypeException");
      
      } catch(TracingAvroTypeException e) {
         //
         // enum value 'a+ROF;z?H80_v' is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      schema_LockableArrayList0.add("nfY");
      Schema schema0 = Schema.createEnum("nfY", "nfY", "nfY", (List<String>) schema_LockableArrayList0);
      int int0 = schema0.getEnumOrdinal("nfY");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      schema_LockableArrayList0.add("nfY");
      Schema schema0 = Schema.createEnum("nfY", "nfY", "nfY", (List<String>) schema_LockableArrayList0);
      boolean boolean0 = schema0.hasEnumSymbol("nfY");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("nfY", "nfY", "nfY", (List<String>) schema_LockableArrayList0);
      boolean boolean0 = schema0.hasEnumSymbol("nfY");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      // Undeclared exception!
      try { 
        Schema.createEnum("error", "] (for ", "] (for ", (List<String>) schema_LockableArrayList0, "] (for ");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // The Enum Default: ] (for  is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      String string0 = "lenient";
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      schema_LockableArrayList0.add(string0);
      schema_LockableArrayList0.add(string0);
      // Undeclared exception!
      try { 
        Schema.createEnum(string0, string0, string0, (List<String>) schema_LockableArrayList0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Duplicate enum symbol: lenient
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord("aliases", ">e)", "A", false, (List<Schema.Field>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("aliases", schema0);
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      linkedList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema1.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"fields\":[{\"name\":\"aliases\",\"type\":{\"type\":\"record\",\"name\":\"aliases\",\"namespace\":\"A\",\"doc\":\">e)\",\"fields\":[]}}]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      assertTrue(schema1.equals((Object)schema0));
      
      schema1.addProp("No field name", "LlI|@H J9q`s5B##36");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Schema schema0 = Schema.createRecord("W", "og.apache.avro.Schema$StringSchema", "com.fasterxml.jackson.core.base.GeneratorBase", true);
      Schema.Field schema_Field0 = new Schema.Field("W", schema0, "W");
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      linkedList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema1.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema0.setFields(linkedList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Fields are already set
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      boolean boolean0 = schema0.hasFields();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      String string0 = "P";
      Schema schema0 = Schema.createRecord("P", "P", "P", true);
      // Undeclared exception!
      try { 
        schema0.getField(string0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = schema0.getField((String) null);
      assertNull(schema_Field0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name("fY", "fY");
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(schema_Name0, "fY");
      boolean boolean0 = schema_SeenPair0.equals("fY");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Schema schema0 = Schema.createRecord("lenfent", "lenfent", "lenfent", true);
      String string0 = "`t7&\\";
      // Undeclared exception!
      try { 
        schema0.addAlias(string0, string0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Illegal initial character: `t7&\\
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      String string0 = "lenient";
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias("lenient");
      schema0.addAlias(string0);
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.createRecord("long", "long", (String) null, true);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Schemas may not be named after primitives: long
         //
         verifyException("org.apache.avro.Schema$NamedSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      String string0 = "ARRAY";
      Schema.Name schema_Name0 = new Schema.Name("ARRAY", "ARRAY");
      String string1 = schema_Name0.getQualified(string0);
      assertEquals("ARRAY", string1);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      List<MapperFeature> list0 = List.of();
      Schema.Name schema_Name0 = new Schema.Name("ARRAY", "ARRAY");
      boolean boolean0 = schema_Name0.equals(list0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("org.apache.avro.compiler.UnresolvedSchema_352", "fixed");
      schema0.addAlias("U.logicalType");
      // Undeclared exception!
      try { 
        schema0.getEnumDefault();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"record\",\"name\":\"UnresolvedSchema_192\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"org.apache.avro.compiler.UnresolvedSchema_352\",\"aliases\":[\"U.logicalType\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Schema schema0 = Schema.createRecord("P", "P", "P", true);
      Schema.Field schema_Field0 = new Schema.Field("P", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
      
      schema_Field1.addProp("JRg`t;V", "P");
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord("oo", "type", "7l5D'6u(tJN", true, (List<Schema.Field>) arrayList0);
      Schema.Field schema_Field0 = new Schema.Field("oo", schema0, "7l5D'6u(tJN");
      boolean boolean0 = schema_Field0.equals(schema_Field0);
      assertEquals("7l5D'6u(tJN", schema_Field0.doc());
      assertTrue(boolean0);
      assertEquals("type", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Schema schema0 = Schema.createRecord("lenient", "lenient", "lenient", true);
      Schema.Field schema_Field0 = new Schema.Field("lenient", schema0, "lenient");
      Set<String> set0 = schema_Field0.aliases();
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Schema schema0 = Schema.createRecord("lenient", "lenient", "lenient", true);
      Schema.Field schema_Field0 = new Schema.Field("lenient", schema0, "lenient");
      schema_Field0.addAlias("Q$Kr95H");
      Set<String> set0 = schema_Field0.aliases();
      assertTrue(set0.contains("Q$Kr95H"));
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      Long long0 = new Long((-609L));
      ValueNode valueNode0 = jsonNodeFactory0.numberNode(long0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("INT", schema0, "7@K2g7^#7`)}![M@(", valueNode0, false, schema_Field_Order0);
      boolean boolean0 = schema_Field0.hasDefaultValue();
      assertTrue(boolean0);
      assertEquals("7@K2g7^#7`)}![M@(", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("%LU3Et$X:;f", (Schema) null, "$", object0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Illegal initial character: %LU3Et$X:;f
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "NULL", "NULL", 7);
      Schema.Field schema_Field0 = new Schema.Field("NULL", schema0, "lenient.lenient", "NULL");
      assertEquals("lenient.lenient", schema_Field0.doc());
      assertEquals("NULL", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      String string0 = "P";
      Schema schema0 = Schema.createRecord("P", "P", "P", true);
      Schema.Field schema_Field0 = new Schema.Field(string0, schema0);
      schema_Field0.addAlias(string0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Schema schema0 = Schema.createRecord("P", "P", "P", true);
      Schema.Field schema_Field0 = new Schema.Field("P", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      boolean boolean0 = schema_Field1.equals(schema_Field0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      boolean boolean0 = schema0.isNullable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema0.hashCode();
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Parser schema_Parser0 = new Schema.Parser();
      Schema schema1 = schema_Parser0.parseInternal("\"string\"");
      assertTrue(schema1.equals((Object)schema0));
      
      schema1.addProp("\"string\"", "\"string\"");
      Schema.applyAliases(schema1, schema0);
      assertFalse(schema1.equals((Object)schema0));
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      ArrayList<Schema.Field> arrayList0 = new ArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord("oo", "type", "7l5D'6u(tJN", true, (List<Schema.Field>) arrayList0);
      Schema schema1 = Protocol.SYSTEM_ERROR;
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertEquals("type", schema0.getDoc());
      assertEquals(Schema.Type.STRING, schema2.getType());
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      HashSet<String> hashSet0 = new HashSet<String>();
      boolean boolean0 = schema0.equals(hashSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Parser schema_Parser0 = new Schema.Parser();
      Schema schema1 = schema_Parser0.parseInternal("\"string\"");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema0));
      assertTrue(schema_Parser0.getValidateDefaults());
      assertNotSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      HashSet<String> hashSet0 = new HashSet<String>();
      String string0 = schema0.toString((Set<String>) hashSet0, false);
      assertEquals("\"string\"", string0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema[] schemaArray0 = new Schema[19];
      schemaArray0[0] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "NULL", "NULL", 7);
      ArrayList<Schema> arrayList0 = new ArrayList<Schema>();
      arrayList0.add(schema0);
      String string0 = schema0.toString((Collection<Schema>) arrayList0, true);
      assertEquals("\"NULL.P\"", string0);
      assertEquals("NULL", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.MAP;
      // Undeclared exception!
      try { 
        Schema.create(schema_Type0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't create a: MAP
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      String string0 = schema_Type0.getName();
      assertEquals("long", string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      boolean boolean0 = schema0.isValidDefault(objectNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ArrayNode arrayNode0 = jsonNodeFactory0.arrayNode();
      boolean boolean0 = schema0.isValidDefault(arrayNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("long", "long");
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      ObjectNode objectNode0 = jsonNodeFactory0.objectNode();
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.ASCENDING;
      Schema.Field schema_Field0 = new Schema.Field("long", schema0, "size", objectNode0, false, schema_Field_Order0);
      schema_Field0.addAlias("size");
      schema_Field0.addAlias("org.apache.avro.compiler.UnresolvedSchema_341");
      assertEquals("size", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Schema schema0 = Schema.parse("{\"type\":\"array\",\"items\":\"string\"}", false);
      assertEquals(Schema.Type.ARRAY, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(4298);
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      LinkedHashSet<Schema> linkedHashSet0 = new LinkedHashSet<Schema>();
      Schema schema1 = Schema.createArray(schema0);
      linkedHashSet0.add(schema1);
      boolean boolean0 = schema0.equalCachedHash(schema1);
      //  // Unstable assertion: assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Schema schema0 = Schema.createFixed("P", "P", "P", 7);
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.resolve(schema0);
      assertTrue(schema1.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      String string0 = schema0.getFullName();
      assertEquals("union[string]", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Integer integer0 = schema0.getIndexNamed("org.apache.avro.compiler");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addProp("k%Oa,akt]", "k%Oa,akt]");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't set properties on a union: [\"string\"]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("G7Z_^B&@8B");
      String string0 = schema_Names0.space();
      assertEquals("G7Z_^B&@8B", string0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema schema0 = schema_Names0.get("dH");
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("");
      schema_Names0.space("N; '?'9");
      assertEquals(0, schema_Names0.size());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("nfY", "nfY", "com.fasterxml.jackson.databind.node.IntNode.UnresolvedSchema", (List<String>) schema_LockableArrayList0);
      schema0.getEnumSymbols();
      assertEquals("nfY", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("nfY", "nfY", "nfY", (List<String>) schema_LockableArrayList0);
      int int0 = schema0.computeHash();
      //  // Unstable assertion: assertEquals((-736818292), int0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      schema_Parser0.getTypes();
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names((String) null);
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(1158);
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      schema_Names0.put(schema_Name0, schema0);
      // Undeclared exception!
      try { 
        schema_Names0.put(schema_Name0, (Schema) null);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Can't redefine: null
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      TreeSet<String> treeSet0 = new TreeSet<String>();
      // Undeclared exception!
      try { 
        schema0.fieldsToJson(treeSet0, "U|3", (JsonGenerator) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      String string0 = "P";
      List<String> list0 = List.of(string0);
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(list0);
      Schema schema0 = Schema.createEnum(string0, string0, string0, (List<String>) schema_LockableArrayList0, string0);
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.core.JsonFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.hasEnumSymbol("v");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      // Undeclared exception!
      try { 
        schema0.setFields(schema_LockableArrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("FLOAT", "FLOAT");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      boolean boolean0 = Schema.getValidateDefaults();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("og.apache.avro.Schema$StringSchema", "og.apache.avro.Schema$StringSchema");
      Collection<Schema> collection0 = null;
      String string0 = schema0.toString(collection0, boolean0);
      //  // Unstable assertion: assertEquals("{\n  \"type\" : \"record\",\n  \"name\" : \"UnresolvedSchema_6\",\n  \"namespace\" : \"org.apache.avro.compiler\",\n  \"doc\" : \"unresolved schema\",\n  \"fields\" : [ ],\n  \"org.apache.avro.idl.unresolved.name\" : \"og.apache.avro.Schema$StringSchema\"\n}", string0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getFixedSize();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not fixed: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("com.fasterxml.jackson.databind.util.StdDateFormat");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      String string0 = schema0.getDoc();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getElementType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an array: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getNamespace();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.hasFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      // Undeclared exception!
      try { 
        Schema.parse((InputStream) byteArrayInputStream0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 0)): only regular white space (\\r, \\n, \\t) is allowed between tokens
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 2]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parseJsonToObject((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.fasterxml.jackson.core.JsonFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a map: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getTypes();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getIndexNamed("org.apache.avro.compiler.UnresolvedSchema_291");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getAliases();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.getField("YP.9a%M");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      Schema.setValidateDefaults(false);
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Schema schema0 = Schema.createRecord("lenient", "lenient", "lenient", true);
      LogicalType logicalType0 = new LogicalType("lenient");
      Schema schema1 = logicalType0.addToSchema(schema0);
      assertFalse(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.isError();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      String string0 = "fY";
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("fY", "fY", "fY", (List<String>) schema_LockableArrayList0);
      Schema schema1 = Schema.createMap(schema0);
      // Undeclared exception!
      try { 
        schema1.getEnumOrdinal(string0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"map\",\"values\":{\"type\":\"enum\",\"name\":\"fY\",\"namespace\":\"fY\",\"doc\":\"fY\",\"symbols\":[]}}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      String string0 = "nfY";
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("nfY", "nfY", "nfY", (List<String>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field(string0, schema0, string0);
      int int0 = schema_Field0.pos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      String string0 = "P";
      Schema schema0 = Schema.createRecord("P", "P", "P", true);
      Schema.Field schema_Field0 = new Schema.Field(string0, schema0);
      Object object0 = schema_Field0.defaultVal();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema.Field schema_Field0 = new Schema.Field("NULL", schema0, "NULL");
      linkedList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      schema1.hashCode();
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("NULL", schema0, "NULL");
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      linkedList0.add(schema_Field0);
      Schema.createRecord((List<Schema.Field>) linkedList0);
      // Undeclared exception!
      try { 
        Schema.createRecord((List<Schema.Field>) linkedList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Field already used: NULL type:UNION pos:0
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Locale locale0 = Locale.GERMANY;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.addAll(267, (Collection<? extends String>) set0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 267, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.addAll((Collection<? extends Schema.Field>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      boolean boolean0 = schema_LockableArrayList0.remove((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Schema schema0 = Schema.parse("[\"string\"]", false);
      assertEquals(Schema.Type.UNION, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      Schema.LockableArrayList<CoercionAction> schema_LockableArrayList0 = new Schema.LockableArrayList<CoercionAction>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.remove(42);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      ObjectMapper objectMapper0 = new ObjectMapper();
      ObjectNode objectNode0 = objectMapper0.createObjectNode();
      Set<String> set0 = Schema.parseAliases(objectNode0);
      boolean boolean0 = schema_LockableArrayList0.removeAll(set0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema.LockableArrayList<Object> schema_LockableArrayList1 = new Schema.LockableArrayList<Object>();
      boolean boolean0 = schema_LockableArrayList0.retainAll(schema_LockableArrayList1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema.Field schema_Field0 = new Schema.Field("NULL", schema0, "NULL");
      linkedList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Object object0 = schema1.writeReplace();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      Schema schema0 = Schema.createRecord("lenient", "lenient", "lenient", true);
      Schema schema1 = Schema.createMap(schema0);
      // Undeclared exception!
      try { 
        schema1.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      String[] stringArray0 = new String[6];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("{\n  \"type\" : \"map\",\n  \"values\" : \"string\"\n}", stringArray0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // dangling content after end of schema: nullnullnullnullnullnull
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }
}
