/*
 * This file was automatically generated by EvoSuite
 * Wed May 27 09:36:52 CEST 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.fasterxml.jackson.core.JsonEncoding;
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.StreamReadFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.JsonNodeFactory;
import com.fasterxml.jackson.databind.node.NumericNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.File;
import java.io.InputStream;
import java.nio.file.Path;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.Stack;
import java.util.Vector;
import org.apache.avro.AvroRuntimeException;
import org.apache.avro.AvroTypeException;
import org.apache.avro.LogicalType;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.SchemaParseException;
import org.apache.avro.path.TracingAvroTypeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(resetStaticState = false, separateClassLoader = false) 
public class Schema_C4_ESTest extends Schema_C4_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      schema0.addAlias("org.apache.avro.compiler.UnresolvedSchema_134");
      assertNull(schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Schema schema0 = Schema.createFixed("org.apache.avro.compiler.UnresolvedSchema_345", "", "org.apache.avro.compiler.UnresolvedSchema_345", 1);
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      String string0 = schema0.toString(set0, true);
      assertTrue(set0.contains("org.apache.avro.compiler.UnresolvedSchema_345"));
      assertEquals("{\n  \"type\" : \"fixed\",\n  \"name\" : \"UnresolvedSchema_345\",\n  \"namespace\" : \"org.apache.avro.compiler\",\n  \"doc\" : \"\",\n  \"size\" : 1\n}", string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      schema0.addProp("dZFX\"\"~", "dZFX\"\"~");
      String string0 = schema0.toString();
      assertEquals("{\"type\":\"string\",\"dZFX\\\"\\\"~\":\"dZFX\\\"\\\"~\"}", string0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Schema schema0 = Schema.parse("{\"type\":\"map\",\"values\":[\"string\"]}");
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      JsonNodeFactory jsonNodeFactory0 = new JsonNodeFactory(false);
      NumericNode numericNode0 = jsonNodeFactory0.numberNode((byte)31);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("s", schema1, "s", numericNode0, false, schema_Field_Order0);
      Schema.Field schema_Field1 = null;
      try {
        schema_Field1 = new Schema.Field(schema_Field0, schema1);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field s: 31 not a {\"type\":\"map\",\"values\":[\"string\"]}
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      boolean boolean0 = schema0.isNullable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      boolean boolean0 = schema0.equals(parseContext0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("STRING", schema0, "STRING");
      schema_LockableArrayList0.lock();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.add(schema_Field0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$LockableArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("mqO", schema0);
      schema_Field0.addAlias("mqO");
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertNotSame(schema2, schema0);
      assertFalse(schema1.equals((Object)schema0));
      assertTrue(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("3");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Schema not yet supported: 3
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"mqO\",\"doc\":\"\"}}}}");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Record has no fields: {\"type\":\"record\",\"name\":\"mqO\",\"doc\":\"\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Schema schema0 = Schema.parse("{\"type\":\"enum\",\"name\":\"iRIG\",\"namespace\":\"iRIG\",\"doc\":\"iRIG\",\"symbols\":[]}");
      assertEquals(Schema.Type.ENUM, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"error\"}", false);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // No name in schema: {\"type\":\"error\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      ObjectMapper objectMapper0 = Schema.MAPPER;
      ObjectNode objectNode0 = objectMapper0.createObjectNode();
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("long", schema0, "long", objectNode0, true, schema_Field_Order0);
      assertEquals("long", schema_Field0.name());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      Schema.Names schema_Names0 = new Schema.Names("symls");
      Schema.Field schema_Field0 = new Schema.Field("symls", schema1, "symls", schema_Names0);
      assertTrue(schema_Field0.hasDefaultValue());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("enum", schema1, "=^01=/9\"U\"w_F7", "string", schema_Field_Order0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field enum: \"string\" not a {\"type\":\"array\",\"items\":[\"string\"]}
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("m8qO", "null", "null", (List<String>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("m8qO", schema0, "m8qO", "null");
      assertEquals("null", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema.Type schema_Type1 = Schema.Type.BOOLEAN;
      Schema schema0 = Schema.create(schema_Type1);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("SRIN", schema0, "SRIN", schema_Type0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field SRIN: \"DOUBLE\" not a \"boolean\"
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("mqO", schema0, "mqO", schema_LockableArrayList0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field mqO: [] not a \"double\"
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("O", schema0, "O", "O");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field O: \"O\" not a \"float\"
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Field schema_Field0 = new Schema.Field("mqO", schema0, "u0i-FGo-]b", "u0i-FGo-]b");
      assertEquals("u0i-FGo-]b", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      Schema schema0 = Schema.createEnum("m8qO", "null", "null", (List<String>) schema_LockableArrayList0);
      boolean boolean0 = schema0.isValidDefault((JsonNode) null);
      assertEquals("null", schema0.getDoc());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      Schema.Name schema_Name0 = new Schema.Name("fields", "fields");
      schema_Names0.put(schema_Name0, (Schema) null);
      schema_Names0.put(schema_Name0, (Schema) null);
      assertEquals("fields.fields", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Schema schema0 = Schema.createRecord("mqO", "mqO", "mqO", false);
      Schema.Names schema_Names0 = new Schema.Names((String) null);
      Schema.Name schema_Name0 = new Schema.Name((String) null, (String) null);
      schema_Names0.put(schema_Name0, schema0);
      // Undeclared exception!
      try { 
        schema_Names0.put(schema_Name0, (Schema) null);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Can't redefine: null
         //
         verifyException("org.apache.avro.Schema$Names", e);
      }
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Names schema_Names0 = new Schema.Names();
      boolean boolean0 = schema_Names0.contains(schema0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("com.fasterxml.jackson.databind.introspect");
      Schema schema0 = schema_Names0.get("com.fasterxml.jackson.databind.introspect");
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("com.fasterxml.jackson.databind.introspect");
      Schema.Name schema_Name0 = new Schema.Name("com.fasterxml.jackson.databind.introspect", ", ");
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      schema_Names0.put(schema_Name0, schema0);
      Schema schema1 = schema_Names0.get("com.fasterxml.jackson.databind.introspect");
      assertFalse(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("G{+./s$g_'o;%K2");
      Schema schema0 = schema_Names0.get("double");
      assertFalse(schema0.isUnion());
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      // Undeclared exception!
      try { 
        schema_Names0.get("{\n  \"type\" : \"fixed\",\n  \"name\" : \"UnresolvedSchema_345\",\n  \"namespace\" : \"org.apache.avro.compiler\",\n  \"doc\" : \"\",\n  \"size\" : 1\n}");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Illegal character in: compiler\",
         //   \"doc\" : \"\",
         //   \"size\" : 1
         // }
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Schema schema0 = Schema.parse("[\"string\"]", true);
      assertEquals(Schema.Type.UNION, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"enum\",\"name\":\"iRIdG\",\"namespace\":\"-INF\",\"doc\":\"04{\"k5j\",\"symbols\":[]}", false);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unexpected character ('k' (code 107)): was expecting comma to separate Object entries
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 61]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("\"string\".enum");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // dangling content after end of schema: .enum
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      schema_Parser0.parseInternal("[\"string\"]");
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        schema_Parser0.parse("m4Pq", stringArray0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'm4Pqnullnullnullnull': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
         //
         verifyException("org.apache.avro.Schema$Parser", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ParseContext parseContext0 = new ParseContext();
      Schema.Parser schema_Parser0 = new Schema.Parser(parseContext0);
      List<Schema> list0 = List.of(schema0, schema0, schema0, schema0);
      // Undeclared exception!
      try { 
        schema_Parser0.addTypes((Iterable<Schema>) list0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // You can only put a named schema into the context
         //
         verifyException("org.apache.avro.ParseContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema[] schemaArray0 = new Schema[9];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      Schema schema1 = Schema.createFixed((String) null, (String) null, (String) null, 1843);
      schemaArray0[2] = schema1;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Schema schema0 = Schema.createFixed("com.fasterxml.jackson.databind.exc.InvalidTypeIdException", "com.fasterxml.jackson.databind.exc.InvalidTypeIdException", "Y:nKtufK%K", 3);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertEquals("com.fasterxml.jackson.databind.exc.InvalidTypeIdException", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createFixed("org.apache.avro.compiler.UnresolvedSchema_318", "org.apache.avro.compiler.UnresolvedSchema_318", "[\"string\"]", 114);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.equals((Object)schema0));
      assertFalse(schema2.isUnion());
      assertEquals("org.apache.avro.compiler.UnresolvedSchema_318", schema2.getDoc());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertSame(schema2, schema1);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertTrue(schema1.isUnion());
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema[] schemaArray0 = new Schema[2];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Duplicate in union:string
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema2 = parseContext0.resolve(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema0));
      assertFalse(schema0.equals((Object)schema2));
      assertSame(schema3, schema1);
      assertTrue(schema3.equals((Object)schema2));
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertFalse(schema3.equals((Object)schema2));
      assertNotSame(schema3, schema2);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      NameValidator nameValidator0 = Schema.getNameValidator();
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema2 = parseContext0.resolve(schema1);
      Schema schema3 = Schema.applyAliases(schema1, schema2);
      assertTrue(schema3.equals((Object)schema2));
      assertSame(schema3, schema1);
      assertFalse(schema0.equals((Object)schema1));
      assertFalse(schema3.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      schema0.addAlias("lNng", "lNng");
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("IGRE", "IGRE", "IGRE", (List<String>) arrayList0);
      Schema schema1 = Schema.createEnum("IGRE", "IGRE", "SIMPLE_NAME", (List<String>) arrayList0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertNotSame(schema2, schema1);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0);
      boolean boolean0 = schema0.equals(stack0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Vector<String> vector0 = new Vector<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) vector0);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      assertSame(schema1, schema0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("IGNORE", "IGNORE", "IGNORE", (List<String>) arrayList0);
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("IGNORE");
        fail("Expecting exception: TracingAvroTypeException");
      
      } catch(TracingAvroTypeException e) {
         //
         // enum value 'IGNORE' is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      arrayList0.add("IGNORE");
      Schema schema0 = Schema.createEnum("IGNORE", "IGNORE", "IGNORE", (List<String>) arrayList0);
      int int0 = schema0.getEnumOrdinal("IGNORE");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema0 = Schema.createEnum("IGRE", "IGRE", "IGRE", (List<String>) arrayList0);
      boolean boolean0 = schema0.hasEnumSymbol("IGRE");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      schema_LockableArrayList0.add("xcP7xEMx7");
      Schema schema0 = Schema.createEnum("xcP7xEMx7", "null", "", (List<String>) schema_LockableArrayList0, "xcP7xEMx7");
      assertEquals("null", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      List<String> list0 = List.of("int", "int", "T@:EbV", "!<g}Z)%l");
      // Undeclared exception!
      try { 
        Schema.createEnum("org.apache.avro.compiler.UnresolvedSchema_5", "org.apache.avro.compiler.UnresolvedSchema_5", "org.apache.avro.compiler.UnresolvedSchema_5", list0, "L5VPANv<~Qwee)(");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Duplicate enum symbol: int
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      stack0.add("bytegrs");
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0);
      String string0 = schema0.toString();
      assertEquals("{\"type\":\"enum\",\"symbols\":[\"bytegrs\"]}", string0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("mqO", schema0);
      schema_Field0.addAlias("mqO");
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      String string0 = schema1.toString();
      assertEquals("{\"type\":\"record\",\"fields\":[{\"name\":\"mqO\",\"type\":{\"type\":\"record\",\"fields\":[]},\"aliases\":[\"mqO\"]}]}", string0);
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.find("RECORD", "4>ET3wdbEEG?zAu");
      Schema[] schemaArray0 = new Schema[4];
      schemaArray0[0] = schema1;
      schemaArray0[1] = schema0;
      schemaArray0[2] = schema1;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Schema schema0 = Schema.createRecord("mqO", "mqO", "mqO", false);
      // Undeclared exception!
      try { 
        schema0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>(411);
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.find("[virtual ", "e[T[&[Mz");
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertEquals("unresolved schema", schema1.getDoc());
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) linkedList0);
      Schema.Field schema_Field0 = new Schema.Field("size", schema0, (String) null);
      Schema.Field[] schema_FieldArray0 = new Schema.Field[2];
      schema_FieldArray0[0] = schema_Field0;
      schema_FieldArray0[1] = schema_Field0;
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>(schema_FieldArray0);
      // Undeclared exception!
      try { 
        Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Field already used: size type:RECORD pos:0
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema0.setFields(schema_LockableArrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Fields are already set
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      boolean boolean0 = schema0.hasFields();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Schema schema0 = Schema.createRecord("mqO", "mqO", "mqO", false);
      Schema schema1 = Schema.createArray(schema0);
      // Undeclared exception!
      try { 
        Schema.applyAliases(schema0, schema1);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Schema schema0 = Schema.createRecord("mqO", "mqO", "mqO", true);
      // Undeclared exception!
      try { 
        schema0.getField((String) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      Schema.Field schema_Field0 = schema0.getField("M7");
      assertNull(schema_Field0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(schema0, (Object) null);
      Schema.SeenPair schema_SeenPair1 = new Schema.SeenPair(schema0, "[\"string\"]");
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(schema0, (Object) null);
      Schema.SeenPair schema_SeenPair1 = new Schema.SeenPair(schema1, "{\"type\":\"map\",\"values\":[\"string\"]}");
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      JsonFactory jsonFactory0 = Schema.FACTORY;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(jsonFactory0, vector0);
      boolean boolean0 = schema_SeenPair0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.SeenPair schema_SeenPair0 = new Schema.SeenPair(schema0, (Object) null);
      boolean boolean0 = schema_SeenPair0.equals(schema_SeenPair0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Stack<Schema.Field> stack0 = new Stack<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) stack0);
      ArrayList<String> arrayList0 = new ArrayList<String>();
      Schema schema1 = Schema.createEnum("I}<.NON_FINAL_AND_ENUMS", "Gqd_5r,g-n%TOY#`/", "7T5[8Ca}q|yz", (List<String>) arrayList0);
      Schema[] schemaArray0 = new Schema[5];
      schemaArray0[0] = schema0;
      schemaArray0[1] = schema0;
      schemaArray0[2] = schema1;
      schemaArray0[3] = schema0;
      schemaArray0[4] = schema1;
      // Undeclared exception!
      try { 
        Schema.createUnion(schemaArray0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Nameless in union:[{\"type\":\"record\",\"fields\":[]},{\"type\":\"record\",\"fields\":[]},{\"type\":\"enum\",\"name\":\"NON_FINAL_AND_ENUMS\",\"namespace\":\"I}<\",\"doc\":\"Gqd_5r,g-n%TOY#`/\",\"symbols\":[]},{\"type\":\"record\",\"fields\":[]},\"I}<.NON_FINAL_AND_ENUMS\"]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      schema0.addAlias("long", "bytes");
      Set<String> set0 = schema0.getAliases();
      assertEquals(1, set0.size());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      schema0.addAlias("long", "bytegrs");
      // Undeclared exception!
      try { 
        schema0.addAlias("1J}$~sdAtT", "long");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Illegal initial character: 1J}$~sdAtT
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.createFixed("null", "", "", (-1));
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Schemas may not be named after primitives: null
         //
         verifyException("org.apache.avro.Schema$NamedSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name("array", "array");
      String string0 = schema_Name0.getQualified("array");
      assertEquals("array.array", string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias((String) null, "org.apae.avro.compiler");
      String string0 = schema0.toString();
      assertEquals("{\"type\":\"record\",\"fields\":[],\"aliases\":[null]}", string0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Schema.Name schema_Name0 = new Schema.Name("s", "&kaw4!+gad%w");
      String string0 = schema_Name0.getQualified("&kaw4!+gad%w");
      assertEquals("s", string0);
      assertEquals("&kaw4!+gad%w.s", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Name schema_Name0 = new Schema.Name("string", "");
      schema_Name0.equals(schema0);
      assertEquals("string", schema_Name0.toString());
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("SRIN", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      assertTrue(schema_Field1.equals((Object)schema_Field0));
      
      schema_Field1.addProp("2143", "2143");
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("SRIN", schema0);
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      boolean boolean0 = schema_Field0.equals(schema_Field1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("iRIdG", schema0, "iRIdG");
      boolean boolean0 = schema_Field0.equals(schema_Field0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("v", schema0, "[\"string\"]", "v", schema_Field_Order0);
      boolean boolean0 = schema_Field0.equals("@#ZZzn>");
      assertEquals("[\"string\"]", schema_Field0.doc());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      Schema.Field schema_Field0 = new Schema.Field("src", schema0, "src");
      schema_Field0.addAlias("G106'f@Ex");
      Set<String> set0 = schema_Field0.aliases();
      assertFalse(set0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) vector0);
      Schema.Field schema_Field0 = new Schema.Field("src", schema0, "src");
      schema_Field0.addAlias("G106'f@Ex");
      schema_Field0.addAlias("G106'f@Ex");
      assertEquals("src", schema_Field0.name());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("ZD=);h?ONuK,V-", schema0, "ZD=);h?ONuK,V-", object0, schema_Field_Order0);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Illegal character in: ZD=);h?ONuK,V-
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Object object0 = Schema.Field.NULL_DEFAULT_VALUE;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("s", schema0, "s", object0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field s: null not a {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Field schema_Field0 = new Schema.Field("mqO", schema0);
      schema_Field0.addAlias("mqO");
      schema_LockableArrayList0.add(schema_Field0);
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema2 = parseContext0.resolve(schema1);
      assertTrue(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0);
      schema0.hashCode = 124;
      Schema schema1 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertTrue(schema2.equals((Object)schema1));
      assertTrue(schema1.equals((Object)schema0));
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.resolve(schema0);
      schema1.hashCode();
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertTrue(schema2.equals((Object)schema1));
      assertSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.createMap(schema0);
      schema0.hashCode();
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.parse("\"string\"");
      assertTrue(schema1.equals((Object)schema0));
      
      schema1.addProp("\"string\"", (Object) "p");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.equals((Object)schema0));
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.applyAliases(schema0, schema1);
      assertFalse(schema2.equals((Object)schema1));
      assertEquals(Schema.Type.BYTES, schema2.getType());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias((String) null, "org.apae.avro.compiler");
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertNotSame(schema2, schema1);
      assertTrue(schema2.equals((Object)schema1));
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.parse("[\"string\"]");
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertTrue(schema2.equals((Object)schema0));
      assertNotSame(schema2, schema0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Stack<Schema> stack0 = new Stack<Schema>();
      String string0 = schema0.toString((Collection<Schema>) stack0, false);
      assertEquals("{\"type\":\"record\",\"fields\":[]}", string0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.ARRAY;
      // Undeclared exception!
      try { 
        Schema.create(schema_Type0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't create a: ARRAY
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      String string0 = schema_Type0.getName();
      assertEquals("null", string0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("mqO", schema0, "mqO", "mqO");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field mqO: \"mqO\" not a \"int\"
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      String string0 = schema0.toString((Collection<Schema>) null, false);
      assertEquals("\"double\"", string0);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("O", schema0, "O", "O");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field O: \"O\" not a \"long\"
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Schema schema0 = Schema.parse("{\"type\":\"array\",\"items\":[\"string\"]}");
      assertEquals(Schema.Type.ARRAY, schema0.getType());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      schema1.hashCode();
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Schema schema0 = Schema.createFixed("com.fasterxml.jackson.databind.exc.InvalidTypeIdException", "com.fasterxml.jackson.databind.exc.InvalidTypeIdException", "Y:nKtufK%K", 3);
      schema0.hashCode();
      assertEquals("com.fasterxml.jackson.databind.exc.InvalidTypeIdException", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Schema schema0 = Schema.createFixed("orgapache.avro.compiler.UnresolvedSchema_318", "orgapache.avro.compiler.UnresolvedSchema_318", (String) null, 114);
      int int0 = schema0.getFixedSize();
      assertEquals(114, int0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema[] schemaArray0 = new Schema[6];
      schemaArray0[0] = schema0;
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>(schemaArray0);
      // Undeclared exception!
      try { 
        schema0.toString((Collection<Schema>) schema_LockableArrayList0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Integer integer0 = schema0.getIndexNamed("com.fasterxml.jackson.databind.jsontype.impl");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addProp("com.fasterxml.jackson.databind.InjectableValues$Base", "com.fasterxml.jackson.databind.InjectableValues$Base");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Can't set properties on a union: [\"string\"]
         //
         verifyException("org.apache.avro.Schema$UnionSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("#i2/4zz~V:G8f");
      String string0 = schema_Names0.space();
      assertEquals("#i2/4zz~V:G8f", string0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names();
      boolean boolean0 = schema_Names0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("CLEAR_CURRENT_TOKEN_ON_CLOSE");
      schema_Names0.space("CLEAR_CURRENT_TOKEN_ON_CLOSE");
      assertEquals("CLEAR_CURRENT_TOKEN_ON_CLOSE", schema_Names0.space());
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Schema.Names schema_Names0 = new Schema.Names("src");
      Schema schema0 = schema_Names0.remove((Object) schema_Names0);
      assertNull(schema0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      Schema.Names schema_Names0 = new Schema.Names();
      schema_Names0.add(schema0);
      boolean boolean0 = schema_Names0.contains(schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0);
      List<String> list0 = schema0.getEnumSymbols();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum("com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer", "OWP7QkFWgpobKJ&g", "com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer", (List<String>) stack0);
      schema0.hashCode();
      assertEquals("OWP7QkFWgpobKJ&g", schema0.getDoc());
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      NameValidator nameValidator0 = Schema.getNameValidator();
      Schema.Parser schema_Parser0 = new Schema.Parser(nameValidator0);
      boolean boolean0 = schema_Parser0.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      HashMap<String, Schema> hashMap0 = new HashMap<String, Schema>();
      Schema.Parser schema_Parser1 = schema_Parser0.addTypes((Map<String, Schema>) hashMap0);
      assertTrue(schema_Parser1.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser();
      assertTrue(schema_Parser0.getValidateDefaults());
      
      schema_Parser0.setValidateDefaults(false);
      assertFalse(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      Schema.Parser schema_Parser0 = new Schema.Parser((NameValidator) null);
      schema_Parser0.getTypes();
      assertTrue(schema_Parser0.getValidateDefaults());
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field schema_Field0 = new Schema.Field("v", schema0, "[\"string\"]");
      Schema.Field[] schema_FieldArray0 = new Schema.Field[8];
      Schema.Field schema_Field1 = new Schema.Field(schema_Field0, schema0);
      schema_FieldArray0[0] = schema_Field1;
      schema_FieldArray0[1] = schema_Field0;
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>(schema_FieldArray0);
      // Undeclared exception!
      try { 
        Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Duplicate field v in record null: v type:UNION pos:1 and v type:UNION pos:0.
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) stack0);
      Locale locale0 = Locale.FRENCH;
      Set<String> set0 = locale0.getUnicodeLocaleAttributes();
      // Undeclared exception!
      try { 
        schema0.fieldsToJson(set0, (String) null, (JsonGenerator) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: {\"type\":\"enum\",\"symbols\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("v", schema0, "[\"string\"]", "v", schema_Field_Order0);
      schema_Field0.aliases();
      assertEquals("[\"string\"]", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>();
      // Undeclared exception!
      try { 
        Schema.createEnum("xcP7xEMx7", "null", "", (List<String>) schema_LockableArrayList0, "xcP7xEMx7");
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // The Enum Default: xcP7xEMx7 is not in the enum symbol set: []
         //
         verifyException("org.apache.avro.Schema$EnumSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      // Undeclared exception!
      try { 
        schema0.hasEnumSymbol("GfGJ^7Leq");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: \"string\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.setFields(vector0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias("long", "long");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      boolean boolean0 = Schema.getValidateDefaults();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getFixedSize();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not fixed: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumDefault();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      Schema.createRecord("mqO", "", "", false);
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.addAlias((String) null);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      String string0 = schema0.getDoc();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test133()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      // Undeclared exception!
      try { 
        schema0.getElementType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an array: \"float\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test134()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getNamespace();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test135()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.hasFields();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test136()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse((InputStream) null);
        fail("Expecting exception: SchemaParseException");
      
      } catch(SchemaParseException e) {
         //
         // Cannot parse <null> schema
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test137()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parseJsonToObject("Y<n4}Efn|;kY");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'Y': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
         //  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test138()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getValueType();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a map: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test139()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>(9);
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema0.getTypes();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: {\"type\":\"record\",\"fields\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test140()  throws Throwable  {
      Schema schema0 = Schema.createRecord("mqO", "mqO", "mqO", true);
      // Undeclared exception!
      try { 
        schema0.getEnumSymbols();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: {\"type\":\"error\",\"name\":\"mqO\",\"namespace\":\"mqO\",\"doc\":\"mqO\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test141()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("[v@rtual ", "e[T[&[Mz");
      // Undeclared exception!
      try { 
        schema0.getIndexNamed("e[T[&[Mz");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a union: {\"type\":\"record\",\"name\":\"UnresolvedSchema_254\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"e[T[&[Mz.[v@rtual \"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test142()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      // Undeclared exception!
      try { 
        schema0.getAliases();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a named type: []
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test143()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getField("[\"string\"]");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test144()  throws Throwable  {
      Schema.setValidateDefaults(true);
  }

  @Test(timeout = 4000)
  public void test145()  throws Throwable  {
      ArrayList<Locale.LanguageRange> arrayList0 = new ArrayList<Locale.LanguageRange>();
      Set<String> set0 = Calendar.getAvailableCalendarTypes();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) arrayList0, (Collection<String>) set0);
      Schema schema0 = Schema.createEnum((String) null, "dpwB", "Leading zeroes not allowed", list0);
      LogicalType logicalType0 = new LogicalType("o<=a`7'w|8&eD");
      Schema schema1 = logicalType0.addToSchema(schema0);
      assertEquals("dpwB", schema1.getDoc());
  }

  @Test(timeout = 4000)
  public void test146()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Object object0 = schema0.writeReplace();
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test147()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.isError();
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not a record: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test148()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        schema0.getEnumOrdinal("[\"string\"]");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test149()  throws Throwable  {
      // Undeclared exception!
      try { 
        Schema.parse("{\"type\":\"record\",\"name\":\"UnresolvedSchema_577\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"kl.kl\"}");
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Undefined schema: kl.kl
         //
         verifyException("org.apache.avro.util.SchemaResolver$ResolvingVisitor", e);
      }
  }

  @Test(timeout = 4000)
  public void test150()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) schema_LockableArrayList0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = null;
      try {
        schema_Field0 = new Schema.Field("E2FscxIi", schema0, "com.fasterxml.jackson.databind.node", "E2FscxIi", schema_Field_Order0);
        fail("Expecting exception: AvroTypeException");
      
      } catch(AvroTypeException e) {
         //
         // Invalid default for field E2FscxIi: \"E2FscxIi\" not a []
         //
         verifyException("org.apache.avro.Schema$Field", e);
      }
  }

  @Test(timeout = 4000)
  public void test151()  throws Throwable  {
      Schema schema0 = Schema.createFixed("org.apache.avro.compiler.UnresolvedSchema_345", "", "org.apache.avro.compiler.UnresolvedSchema_345", 1);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.IGNORE;
      Schema.Field schema_Field0 = new Schema.Field("Kj", schema0, "bytes", "bytes", schema_Field_Order0);
      schema_Field0.defaultVal();
      assertEquals("", schema0.getDoc());
      assertEquals("bytes", schema_Field0.doc());
  }

  @Test(timeout = 4000)
  public void test152()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema.Field schema_Field0 = new Schema.Field("IGNORE", schema0);
      schema_LockableArrayList0.add(schema_Field0);
      //  // Unstable assertion: assertEquals((-1), schema_Field0.pos());
      
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      int int0 = schema1.computeHash();
      //  // Unstable assertion: assertEquals(339752424, int0);
  }

  @Test(timeout = 4000)
  public void test153()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      JsonNodeFactory jsonNodeFactory0 = JsonNodeFactory.instance;
      NumericNode numericNode0 = jsonNodeFactory0.numberNode((short)0);
      Schema.Field.Order schema_Field_Order0 = Schema.Field.Order.DESCENDING;
      Schema.Field schema_Field0 = new Schema.Field("ARRAY", schema0, "ARRAY", numericNode0, false, schema_Field_Order0);
      schema_LockableArrayList0.add(schema_Field0);
      assertEquals((-1), schema_Field0.pos());
      
      Schema schema1 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      String string0 = schema1.toString();
      assertEquals("{\"type\":\"record\",\"fields\":[{\"name\":\"ARRAY\",\"type\":[\"string\"],\"doc\":\"ARRAY\",\"default\":0,\"order\":\"descending\"}]}", string0);
  }

  @Test(timeout = 4000)
  public void test154()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.addAll((-1908874352), (Collection<? extends Schema.Field>) schema_LockableArrayList0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: -1908874352, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test155()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Vector<Schema.Field> vector0 = new Vector<Schema.Field>();
      boolean boolean0 = schema_LockableArrayList0.addAll((Collection<? extends Schema.Field>) vector0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test156()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      boolean boolean0 = schema_LockableArrayList0.remove((Object) schema0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test157()  throws Throwable  {
      Schema.LockableArrayList<Schema> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema>();
      // Undeclared exception!
      try { 
        schema_LockableArrayList0.remove(5);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test158()  throws Throwable  {
      Stack<String> stack0 = new Stack<String>();
      Schema.LockableArrayList<String> schema_LockableArrayList0 = new Schema.LockableArrayList<String>(stack0);
      boolean boolean0 = schema_LockableArrayList0.removeAll(stack0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test159()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      LinkedHashSet<StreamReadFeature> linkedHashSet0 = new LinkedHashSet<StreamReadFeature>();
      boolean boolean0 = schema_LockableArrayList0.retainAll(linkedHashSet0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test160()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>(0);
      schema_LockableArrayList0.clear();
      assertEquals(0, schema_LockableArrayList0.size());
  }

  @Test(timeout = 4000)
  public void test161()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      schema1.hashCode();
  }

  @Test(timeout = 4000)
  public void test162()  throws Throwable  {
      Schema.LockableArrayList<Schema.Field> schema_LockableArrayList0 = new Schema.LockableArrayList<Schema.Field>();
      Schema schema0 = Schema.createRecord((List<Schema.Field>) schema_LockableArrayList0);
      schema0.addAlias("ong", "ong");
      Schema schema1 = Schema.createMap(schema0);
      Schema schema2 = Schema.applyAliases(schema1, schema0);
      assertFalse(schema2.equals((Object)schema0));
      assertSame(schema2, schema1);
  }
}
