package org.apache.avro.compiler.specific;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import javax.tools.JavaCompiler;
import javax.tools.ToolProvider;

import org.apache.avro.Schema;
import org.junit.Test;

public class TestNonASCIISpecificCompiler {

  private static final String NON_ASCII_NAMESPACE = "组织.apache";
  private static final String RECORD_NAME = "User";
  private static final String FIELD_NAME = "id";

  private static final String NON_ASCII_SCHEMA_JSON =
      "{"
          + "\"type\":\"record\","
          + "\"namespace\":\"" + NON_ASCII_NAMESPACE + "\","
          + "\"name\":\"" + RECORD_NAME + "\","
          + "\"fields\":["
          + "{\"name\":\"" + FIELD_NAME + "\",\"type\":\"int\"}"
          + "]"
          + "}";

  /*
   * Questo test verifica la vera code generation Avro.
   *
   * Obiettivo:
   * partire da uno schema Avro con namespace non-ASCII, invocare SpecificCompiler
   * e verificare che venga generato un file Java nel path coerente con il namespace.
   *
   * Se questo test passa, allora il namespace non-ASCII non crea problemi
   * almeno nella fase di generazione del sorgente Java.
   */
  @Test
  public void specificCompilerShouldGenerateJavaSourceFromNonAsciiNamespaceSchema() throws Exception {
    Schema schema = new Schema.Parser().parse(NON_ASCII_SCHEMA_JSON);

    Path tempDir = Files.createTempDirectory("avro-non-ascii-specific-compiler-test");
    Path schemaFile = tempDir.resolve("User.avsc");
    Path generatedDir = tempDir.resolve("generated");

    Files.createDirectories(generatedDir);
    Files.write(schemaFile, schema.toString().getBytes(StandardCharsets.UTF_8));

    SpecificCompiler compiler = new SpecificCompiler(schema);
    compiler.compileToDestination(schemaFile.toFile(), generatedDir.toFile());

    Path expectedGeneratedFile =
        generatedDir.resolve("组织").resolve("apache").resolve(RECORD_NAME + ".java");

    assertTrue(
        "Expected SpecificCompiler to generate Java source under path derived from namespace: "
            + expectedGeneratedFile,
        Files.exists(expectedGeneratedFile));
  }

  /*
   * Questo test verifica il contenuto del sorgente generato.
   *
   * Obiettivo:
   * verificare che il file generato contenga effettivamente il package Java
   * derivato dal namespace Avro non-ASCII.
   *
   * Questo è importante perché dimostra che il namespace non-ASCII viene
   * propagato fino al sorgente Java generato.
   */
  @Test
  public void generatedJavaSourceShouldContainNonAsciiPackageDeclaration() throws Exception {
    Path generatedFile = generateJavaSourceFromNonAsciiSchema();

    String generatedSource = new String(Files.readAllBytes(generatedFile), StandardCharsets.UTF_8);

    assertTrue(
        "Expected generated source to contain package declaration with non-ASCII namespace.",
        generatedSource.contains("package " + NON_ASCII_NAMESPACE + ";"));

    assertTrue(
        "Expected generated source to contain generated class declaration.",
        generatedSource.contains("public class " + RECORD_NAME));
  }

  /*
   * Questo test verifica il passo successivo alla code generation:
   * il sorgente Java generato da SpecificCompiler viene passato a javac.
   *
   * Obiettivo:
   * capire se la toolchain Java riesce a compilare il sorgente prodotto da Avro
   * quando il package deriva da un namespace non-ASCII.
   *
   * Se questo test passa, allora non solo Avro genera il file, ma il risultato
   * è anche compilabile dal compilatore Java standard.
   */
  @Test
  public void generatedJavaSourceFromNonAsciiNamespaceShouldCompileWithJavac() throws Exception {
    Path generatedFile = generateJavaSourceFromNonAsciiSchema();

    JavaCompiler javaCompiler = ToolProvider.getSystemJavaCompiler();
    assertTrue("This test requires a JDK with JavaCompiler.", javaCompiler != null);

    Path classesDir = generatedFile.getParent().getParent().getParent().resolve("classes");
    Files.createDirectories(classesDir);

    int compilationResult =
        javaCompiler.run(
            null,
            null,
            null,
            "-encoding",
            "UTF-8",
            "-classpath",
            System.getProperty("java.class.path"),
            "-d",
            classesDir.toString(),
            generatedFile.toString());

    assertEquals(
        "Expected javac to compile the Java source generated by SpecificCompiler.",
        0,
        compilationResult);

    Path expectedClassFile =
        classesDir.resolve("组织").resolve("apache").resolve(RECORD_NAME + ".class");

    assertTrue(
        "Expected compiled class file to exist: " + expectedClassFile,
        Files.exists(expectedClassFile));
  }

  private static Path generateJavaSourceFromNonAsciiSchema() throws Exception {
    Schema schema = new Schema.Parser().parse(NON_ASCII_SCHEMA_JSON);

    Path tempDir = Files.createTempDirectory("avro-non-ascii-specific-compiler-test");
    Path schemaFile = tempDir.resolve("User.avsc");
    Path generatedDir = tempDir.resolve("generated");

    Files.createDirectories(generatedDir);
    Files.write(schemaFile, schema.toString().getBytes(StandardCharsets.UTF_8));

    SpecificCompiler compiler = new SpecificCompiler(schema);
    compiler.compileToDestination(schemaFile.toFile(), generatedDir.toFile());

    Path generatedFile =
        generatedDir.resolve("组织").resolve("apache").resolve(RECORD_NAME + ".java");

    assertTrue(
        "Expected generated Java source to exist: " + generatedFile,
        Files.exists(generatedFile));

    return generatedFile;
  }
}
