/*
 * This file was automatically generated by EvoSuite
 * Thu May 28 15:12:59 CEST 2026
 */

package org.apache.avro.file;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.AbstractMap;
import java.util.LinkedList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import org.apache.avro.AvroRuntimeException;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.file.DataFileStream;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.file.SeekableByteArrayInput;
import org.apache.avro.file.SeekableFileInput;
import org.apache.avro.file.SyncableFileOutputStream;
import org.apache.avro.file.XZCodec;
import org.apache.avro.generic.GenericDatumWriter;
import org.apache.avro.io.BinaryEncoder;
import org.apache.avro.io.DatumReader;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.reflect.ReflectDatumWriter;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.specific.SpecificDatumWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(resetStaticState = false, separateClassLoader = true) 
public class DataFileWriter_C1_ESTest extends DataFileWriter_C1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("avro.java.string", "org.apache.avro.fastread");
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // Cannot set reserved meta key: avro.java.string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      GenericDatumWriter<SeekableByteArrayInput> genericDatumWriter0 = new GenericDatumWriter<SeekableByteArrayInput>();
      DataFileWriter<SeekableByteArrayInput> dataFileWriter0 = new DataFileWriter<SeekableByteArrayInput>(genericDatumWriter0);
      DataFileWriter<SeekableByteArrayInput> dataFileWriter1 = dataFileWriter0.setMeta("9AGb\"ykc", 2842L);
      assertSame(dataFileWriter1, dataFileWriter0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      assertSame(dataFileWriter0, dataFileWriter1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(32768);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>>((DatumWriter<AbstractMap.SimpleImmutableEntry<Object, Object>>) null);
      // Undeclared exception!
      try { 
        dataFileWriter0.appendEncoded(byteBuffer0);
        fail("Expecting exception: AvroRuntimeException");
      
      } catch(AvroRuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      dataFileWriter0.close();
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SpecificData specificData0 = new SpecificData();
      SpecificDatumWriter<FileOutputStream> specificDatumWriter0 = new SpecificDatumWriter<FileOutputStream>((Schema) null, specificData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(specificDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval((-1990));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: -1990
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      XZCodec.Option xZCodec_Option0 = new XZCodec.Option((-753));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setCodec(xZCodec_Option0);
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      boolean boolean0 = dataFileWriter0.isFlushOnEveryBlock();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      dataFileWriter0.setFlushOnEveryBlock(true);
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream(outputStream0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(bufferedOutputStream0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) objectOutputStream0);
      dataFileWriter1.fSync();
  }
}
