/*
 * This file was automatically generated by EvoSuite
 * Thu May 28 14:05:43 GMT 2026
 */

package org.apache.avro.file;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.util.function.Function;
import org.apache.avro.Conversions;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.file.DataFileStream;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.file.ZstandardCodec;
import org.apache.avro.io.BinaryEncoder;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.io.FastReaderBuilder;
import org.apache.avro.reflect.ReflectData;
import org.apache.avro.reflect.ReflectDatumWriter;
import org.apache.avro.specific.SpecificDatumWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = false, separateClassLoader = true) 
public class DataFileWriter_C4_ESTest extends DataFileWriter_C4_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      MockFile mockFile0 = new MockFile("avro.", "avro.");
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Conversions.UUIDConversion conversions_UUIDConversion0 = new Conversions.UUIDConversion();
      Schema schema0 = conversions_UUIDConversion0.getRecommendedSchema();
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (File) mockFile0);
      dataFileWriter1.fSync();
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
      assertEquals(73L, mockFile0.length());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      File file0 = MockFile.createTempFile("org.apache.avro.fastread", "x3m6m");
      dataFileWriter0.create(schema0, file0);
      FastReaderBuilder.RecordReader fastReaderBuilder_RecordReader0 = new FastReaderBuilder.RecordReader();
      FastReaderBuilder.MapReader fastReaderBuilder_MapReader0 = new FastReaderBuilder.MapReader(fastReaderBuilder_RecordReader0, fastReaderBuilder_RecordReader0);
      DataFileStream<Object> dataFileStream0 = new DataFileStream<Object>(fastReaderBuilder_MapReader0);
      // Undeclared exception!
      try { 
        dataFileWriter0.appendAllFrom(dataFileStream0, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      FastReaderBuilder.RecordReader fastReaderBuilder_RecordReader0 = new FastReaderBuilder.RecordReader();
      FastReaderBuilder.MapReader fastReaderBuilder_MapReader0 = new FastReaderBuilder.MapReader(fastReaderBuilder_RecordReader0, fastReaderBuilder_RecordReader0);
      DataFileStream<Object> dataFileStream0 = new DataFileStream<Object>(fastReaderBuilder_MapReader0);
      // Undeclared exception!
      try { 
        dataFileWriter0.appendAllFrom(dataFileStream0, false);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      dataFileWriter0.close();
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectData reflectData0 = new ReflectData((ClassLoader) null);
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("java-key-class", false);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0);
      dataFileWriter1.fSync();
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      MockFile mockFile0 = new MockFile("avro.org.a", "avro.java.string");
      dataFileWriter0.create(schema0, (File) mockFile0);
      assertEquals(43L, mockFile0.length());
      
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(1172);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setSyncInterval(1172);
      dataFileWriter1.appendEncoded(byteBuffer0);
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = ReflectData.get();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("avro.java.string", (long) '$');
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot set reserved meta key: avro.java.string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      File file0 = MockFile.createTempFile("3tA>", "avro.java.string");
      DataFileWriter<Object> dataFileWriter1 = new DataFileWriter<Object>(reflectDatumWriter0);
      ZstandardCodec.Option zstandardCodec_Option0 = new ZstandardCodec.Option(200, true, false);
      dataFileWriter0.setCodec(zstandardCodec_Option0);
      dataFileWriter0.create(schema0, file0);
      dataFileWriter1.appendTo(file0);
      assertEquals(64L, file0.length());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      DataFileWriter<Object> dataFileWriter1 = new DataFileWriter<Object>(reflectDatumWriter0);
      File file0 = MockFile.createTempFile("~2(bMABl", "java-key-class");
      dataFileWriter0.create(schema0, file0);
      dataFileWriter1.appendTo(file0);
      assertEquals(45L, file0.length());
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval(1992383480);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: 1992383480
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval((-88));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: -88
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      MockFile mockFile0 = new MockFile("0$B", "0$B");
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Conversions.UUIDConversion conversions_UUIDConversion0 = new Conversions.UUIDConversion();
      Schema schema0 = conversions_UUIDConversion0.getRecommendedSchema();
      dataFileWriter0.create(schema0, (File) mockFile0);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        dataFileWriter0.append(object0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassCastException: value java.lang.Object@6ab6d5af (a java.lang.Object) cannot be cast to expected type string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      MockFile mockFile0 = new MockFile("avro.", "avro.");
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Conversions.UUIDConversion conversions_UUIDConversion0 = new Conversions.UUIDConversion();
      Schema schema0 = conversions_UUIDConversion0.getRecommendedSchema();
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (File) mockFile0);
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(1670);
      dataFileWriter1.appendEncoded(byteBuffer0);
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
      assertEquals(73L, mockFile0.length());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("3tA>", (long) '$');
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SpecificDatumWriter<FileOutputStream> specificDatumWriter0 = new SpecificDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(specificDatumWriter0);
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
      
      dataFileWriter0.setFlushOnEveryBlock(false);
      assertFalse(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      MockFile mockFile0 = new MockFile("a);=.", "a);=.");
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (File) mockFile0);
      dataFileWriter1.close();
      assertEquals(45L, mockFile0.length());
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      dataFileWriter0.create(schema0, (OutputStream) byteArrayOutputStream0);
      dataFileWriter0.fSync();
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      boolean boolean0 = dataFileWriter0.isFlushOnEveryBlock();
      assertTrue(boolean0);
  }
}
