/*
 * This file was automatically generated by EvoSuite
 * Mon May 18 13:14:38 GMT 2026
 */

package org.apache.avro.file;

import org.junit.Test;
import org.junit.Ignore;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedOutputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileDescriptor;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.io.OutputStream;
import java.io.PipedOutputStream;
import java.io.PrintStream;
import java.math.BigDecimal;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.util.AbstractMap;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.function.Function;
import org.apache.avro.Conversions;
import org.apache.avro.LogicalType;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.data.Json;
import org.apache.avro.file.BZip2Codec;
import org.apache.avro.file.CodecFactory;
import org.apache.avro.file.DataFileReader;
import org.apache.avro.file.DataFileStream;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.file.NullCodec;
import org.apache.avro.file.SeekableByteArrayInput;
import org.apache.avro.file.SeekableFileInput;
import org.apache.avro.file.SeekableInput;
import org.apache.avro.file.SyncableFileOutputStream;
import org.apache.avro.file.XZCodec;
import org.apache.avro.file.ZstandardCodec;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericDatumWriter;
import org.apache.avro.io.BinaryEncoder;
import org.apache.avro.io.BlockingDirectBinaryEncoder;
import org.apache.avro.io.DatumReader;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.io.FastReaderBuilder;
import org.apache.avro.reflect.ReflectData;
import org.apache.avro.reflect.ReflectDatumWriter;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.specific.SpecificDatumWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.System;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.lang.MockException;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false) 
public class DataFileWriter_ESTest extends DataFileWriter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      SpecificDatumWriter<Object> specificDatumWriter1 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter1);
      MockFile mockFile0 = new MockFile("8[HU[!Uvcc)5 *'lq#", "avro.Am%6y");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(mockFile0);
      BlockingDirectBinaryEncoder blockingDirectBinaryEncoder0 = new BlockingDirectBinaryEncoder(syncableFileOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(blockingDirectBinaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, (File) mockFile0);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = charset0.encode("sz2");
      boolean boolean0 = mockFile0.setWritable(false, false);
      try { 
        dataFileWriter2.appendEncoded(byteBuffer0);
      } catch(IOException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.NativeMockedIO", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      SpecificDatumWriter<Object> specificDatumWriter1 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter1);
      MockFile mockFile0 = new MockFile("8[HU[!Uvcc)5 *'lq#", "avro.Am%6y");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(mockFile0);
      BlockingDirectBinaryEncoder blockingDirectBinaryEncoder0 = new BlockingDirectBinaryEncoder(syncableFileOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(blockingDirectBinaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, (File) mockFile0);
      Charset charset0 = Charset.defaultCharset();
      dataFileWriter2.append("sz2");
      ByteBuffer byteBuffer0 = charset0.encode("sz2");
      dataFileWriter2.appendEncoded(byteBuffer0);
      dataFileWriter2.close();
      DataFileWriter<Object> dataFileWriter3 = dataFileWriter0.setMeta("java-class", "org.apache.avro.fastread");
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      boolean boolean0 = false;
      String string0 = "";
      SpecificDatumWriter<FileOutputStream> specificDatumWriter2 = new SpecificDatumWriter<FileOutputStream>(schema0, specificData0);
      DataFileWriter<FileOutputStream> dataFileWriter4 = new DataFileWriter<FileOutputStream>(specificDatumWriter2);
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte)120;
      byteArray0[1] = (byte)4;
      byteArray0[2] = (byte) (-16);
      byteArray0[3] = (byte)58;
      byteArray0[4] = (byte)29;
      DataFileWriter<FileOutputStream> dataFileWriter5 = dataFileWriter4.setMeta("java-key-class", byteArray0);
      try { 
        dataFileWriter5.appendTo((SeekableInput) seekableFileInput0, (OutputStream) byteArrayOutputStream0);
      } catch(IOException e) {
         //
         // Not an Avro data file.
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      SpecificDatumWriter<Object> specificDatumWriter1 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter1);
      MockFile mockFile0 = new MockFile("8[HU[!Uvcc)5 *'lq#", "avro.Am%6y");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(mockFile0);
      BlockingDirectBinaryEncoder blockingDirectBinaryEncoder0 = new BlockingDirectBinaryEncoder(syncableFileOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(blockingDirectBinaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      MockFile mockFile1 = new MockFile("java-key-class");
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, (File) mockFile1);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = charset0.encode("sz2");
      dataFileWriter2.appendEncoded(byteBuffer0);
      dataFileWriter2.close();
      DataFileWriter<Object> dataFileWriter3 = dataFileWriter0.setMeta("java-class", "org.apache.avro.fastread");
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile1);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      MockPrintStream mockPrintStream0 = null;
      try {
        mockPrintStream0 = new MockPrintStream(byteArrayOutputStream0, false, "");
      } catch(Throwable e) {
         //
         // 
         //
         verifyException("java.io.PrintStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      BinaryEncoder binaryEncoder0 = SpecificData.getEncoder((ObjectOutput) null);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(binaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      String string0 = "9rbUU!j2(UK";
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)64;
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter4 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      Random.setNextRandom(1);
      ZstandardCodec.Option zstandardCodec_Option0 = new ZstandardCodec.Option((byte)64, false, false);
      DataFileWriter<Object> dataFileWriter6 = dataFileWriter5.setCodec(zstandardCodec_Option0);
      DataFileWriter<Object> dataFileWriter7 = dataFileWriter6.setEncoder(function0);
      DataFileWriter<Object> dataFileWriter8 = dataFileWriter7.appendTo((File) mockFile0);
      Random.setNextRandom(32);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        dataFileWriter7.append(object0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.specific.ExternalizableOutput", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      System.setCurrentTimeMillis(688L);
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "already open");
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      File file0 = MockFile.createTempFile("4SnLm=&e", "4SnLm=&e");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, true);
      byte[] byteArray0 = new byte[16];
      byteArray0[0] = (byte)106;
      byteArray0[1] = (byte)106;
      byteArray0[2] = (byte)94;
      byteArray0[5] = (byte)82;
      boolean boolean1 = file0.setExecutable(false);
      byteArray0[6] = (byte)70;
      byteArray0[7] = (byte) (-120);
      byteArray0[8] = (byte)86;
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter0.setSyncInterval((byte)106);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = charset0.encode("already open");
      ReflectData reflectData0 = ReflectData.get();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter1 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter3 = new DataFileWriter<FileOutputStream>(reflectDatumWriter1);
      DataFileWriter<FileOutputStream> dataFileWriter4 = dataFileWriter3.setMeta("WRITE_SINGLE_ELEM_ARRAYS_UNWRAPPED", byteArray0);
      NullCodec.Option nullCodec_Option0 = (NullCodec.Option)NullCodec.OPTION;
      DataFileWriter<FileOutputStream> dataFileWriter5 = dataFileWriter4.setCodec(nullCodec_Option0);
      DataFileWriter<FileOutputStream> dataFileWriter6 = dataFileWriter5.setSyncInterval((byte)70);
      DataFileWriter<FileOutputStream> dataFileWriter7 = dataFileWriter6.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter8 = dataFileWriter7.setEncoder(function0);
      dataFileWriter8.fSync();
      Random.setNextRandom((-1115));
      dataFileWriter2.appendEncoded(byteBuffer0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("4SnLm=&e", "4SnLm=&e");
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      mockPrintStream0.print(1953L);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)64;
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter4 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.setMeta("\u0006C", "5DV{;i<34");
      DataFileWriter<Object> dataFileWriter6 = dataFileWriter5.setMeta("java-key-class", (long) (byte) (-15));
      try { 
        dataFileWriter6.appendTo((File) mockFile0);
      } catch(IOException e) {
         //
         // Not an Avro data file.
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "8C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      String string0 = "9rbUU!j2(UK";
      byte[] byteArray0 = new byte[4];
      byte byte0 = (byte)64;
      // Undeclared exception!
      try { 
        dataFileWriter0.appendEncoded((ByteBuffer) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.io.Encoder", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)64;
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter4 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      DataFileWriter<Object> dataFileWriter6 = dataFileWriter5.setMeta("java-key-class", (long) (byte) (-15));
      DataFileWriter<Object> dataFileWriter7 = dataFileWriter5.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> specificDatumWriter0 = new SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<Object, Object>>(schema0, reflectData0);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> dataFileWriter8 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>>(specificDatumWriter0);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> dataFileWriter9 = dataFileWriter8.setMeta("<wLyu", "d?>;[_)v9?YW#Sc`I");
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> dataFileWriter10 = dataFileWriter9.create(schema0, (File) mockFile0);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> dataFileWriter11 = dataFileWriter10.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      Object object0 = new Object();
      AbstractMap.SimpleImmutableEntry<Object, Object> abstractMap_SimpleImmutableEntry0 = new AbstractMap.SimpleImmutableEntry<Object, Object>(object0, dataFileWriter9);
      // Undeclared exception!
      try { 
        dataFileWriter11.append(abstractMap_SimpleImmutableEntry0);
      } catch(RuntimeException e) {
         //
         // java.lang.ClassCastException: value java.lang.Object@6b758571=org.apache.avro.file.DataFileWriter@35 (a java.util.AbstractMap$SimpleImmutableEntry) cannot be cast to expected type string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      String string0 = "9rbUU!j2(UK";
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)64;
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter4 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      Random.setNextRandom(1);
      ZstandardCodec.Option zstandardCodec_Option0 = new ZstandardCodec.Option(16, false, false);
      DataFileWriter<Object> dataFileWriter6 = dataFileWriter5.setCodec(zstandardCodec_Option0);
      DataFileWriter<Object> dataFileWriter7 = dataFileWriter5.setMeta("java-key-class", (long) (byte) (-15));
      // Undeclared exception!
      try { 
        dataFileWriter7.appendTo((File) mockFile0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)64;
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter4 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.setMeta("\u0006C", "5DV{;i<34");
      DataFileWriter<Object> dataFileWriter6 = dataFileWriter5.setMeta("java-key-class", (long) (byte) (-15));
      DataFileWriter<Object> dataFileWriter7 = dataFileWriter6.appendTo((File) mockFile0);
      Random.setNextRandom(990);
      dataFileWriter4.fSync();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      PrintStream printStream0 = mockPrintStream0.append('_');
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      Charset charset0 = Charset.defaultCharset();
      boolean boolean1 = Charset.isSupported("avro.java.string");
      ByteBuffer byteBuffer0 = charset0.encode("avro.start-union");
      dataFileWriter3.appendEncoded(byteBuffer0);
      String string0 = "9rbUU!j2(UK";
      String string1 = "5DV{;i<34";
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(datumReader0);
      // Undeclared exception!
      try { 
        dataFileWriter1.appendAllFrom(dataFileStream0, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      System.setCurrentTimeMillis(688L);
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      File file0 = MockFile.createTempFile("4SnLm=&e", "4SnLm=&e");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, true);
      byte[] byteArray0 = new byte[16];
      byteArray0[0] = (byte)106;
      byteArray0[1] = (byte)106;
      byteArray0[2] = (byte) (-118);
      byteArray0[3] = (byte)82;
      byteArray0[4] = (byte)12;
      byteArray0[5] = (byte)82;
      byteArray0[6] = (byte)70;
      byteArray0[7] = (byte) (-120);
      byteArray0[8] = (byte)86;
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter0.setSyncInterval((byte)106);
      dataFileWriter2.close();
      DataFileWriter<Object> dataFileWriter3 = dataFileWriter0.setMeta("4SnLm=&e", "4SnLm=&e");
      DataFileWriter<Object> dataFileWriter4 = dataFileWriter3.appendTo(file0);
      // Undeclared exception!
      try { 
        dataFileWriter4.setMeta("avro.avro.*xCrt,M)Z0{uIn", (-2103L));
      } catch(RuntimeException e) {
         //
         // Cannot set reserved meta key: avro.avro.*xCrt,M)Z0{uIn
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificDatumWriter<SeekableFileInput> specificDatumWriter0 = new SpecificDatumWriter<SeekableFileInput>(schema0);
      DataFileWriter<SeekableFileInput> dataFileWriter0 = new DataFileWriter<SeekableFileInput>(specificDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval(1073741834);
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: 1073741834
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      String string0 = "9rbUU!j2(UK";
      String string1 = "5DV{;i<34";
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)64;
      byte byte0 = (byte) (-15);
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter4 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      DataFileWriter<Object> dataFileWriter6 = dataFileWriter5.setMeta("java-key-class", (long) (byte) (-15));
      // Undeclared exception!
      try { 
        dataFileWriter6.appendTo((File) mockFile0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      System.setCurrentTimeMillis(688L);
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      File file0 = MockFile.createTempFile("4SnLm=&e", "4SnLm=&e");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, true);
      byte[] byteArray0 = new byte[16];
      byteArray0[0] = (byte)106;
      byteArray0[1] = (byte)48;
      byteArray0[2] = (byte) (-124);
      byteArray0[3] = (byte)82;
      byteArray0[4] = (byte)12;
      byteArray0[5] = (byte) (-120);
      byteArray0[6] = (byte)70;
      byteArray0[7] = (byte) (-82);
      byteArray0[8] = (byte)86;
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.setSyncInterval((byte)106);
      // Undeclared exception!
      try { 
        dataFileWriter2.create(schema0, (OutputStream) mockFileOutputStream0);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      System.setCurrentTimeMillis(688L);
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      File file0 = MockFile.createTempFile("4SnLm=&e", "4SnLm=&e");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(file0, true);
      byte[] byteArray0 = new byte[9];
      byteArray0[0] = (byte)106;
      byteArray0[1] = (byte)48;
      byteArray0[2] = (byte) (-124);
      byteArray0[3] = (byte)82;
      byteArray0[4] = (byte)12;
      byteArray0[5] = (byte) (-120);
      byteArray0[6] = (byte)70;
      byteArray0[7] = (byte) (-82);
      byteArray0[8] = (byte) (-24);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("4SnLm=&e", (long) (byte)12);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.setSyncInterval((byte)106);
      DataFileWriter<Object> dataFileWriter3 = dataFileWriter2.create(schema0, (OutputStream) mockFileOutputStream0);
      // Undeclared exception!
      try { 
        dataFileWriter3.appendTo(file0);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter2.fSync();
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter1.setEncoder(function0);
      String string0 = "9rbUU!j2(UK";
      String string1 = "5DV{;i<34";
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(datumReader0);
      // Undeclared exception!
      try { 
        dataFileWriter1.appendAllFrom(dataFileStream0, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      SpecificDatumWriter<SeekableFileInput> specificDatumWriter0 = new ReflectDatumWriter<SeekableFileInput>(schema0);
      DataFileWriter<SeekableFileInput> dataFileWriter0 = new DataFileWriter<SeekableFileInput>(specificDatumWriter0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      byte[] byteArray0 = new byte[2];
      DataFileWriter<SeekableFileInput> dataFileWriter1 = dataFileWriter0.setSyncInterval(1073741823);
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter2.setMeta("I4F", byteArray0);
      DataFileWriter<FileOutputStream> dataFileWriter4 = dataFileWriter3.setSyncInterval(1073741823);
      DataFileWriter<FileOutputStream> dataFileWriter5 = dataFileWriter4.create(schema0, (OutputStream) byteArrayOutputStream0);
      // Undeclared exception!
      try { 
        dataFileWriter5.setMeta("I4F", (long) 1073741823);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      MockFile mockFile0 = new MockFile("8[HU[!Uvcc)5 *'lq#", "avro.Am%6y");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(mockFile0);
      BlockingDirectBinaryEncoder blockingDirectBinaryEncoder0 = new BlockingDirectBinaryEncoder(syncableFileOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(blockingDirectBinaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      MockFile mockFile1 = new MockFile("java-key-class");
      File file0 = MockFile.createTempFile("]NM<w.%P~HYwv=", "Mb3RpLG`6f0C4W03yFh", (File) mockFile1);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, file0);
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        dataFileWriter2.close();
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      boolean boolean0 = FileSystemHandling.createFolder((EvoSuiteFile) null);
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("^A?ek", "^A?ek");
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter1.setEncoder(function0);
      Schema schema0 = Schema.createArray((Schema) null);
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream("avro.9rbUUUj2^(UK");
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-2);
      byteArray0[1] = (byte)0;
      byteArray0[2] = (byte)23;
      // Undeclared exception!
      try { 
        dataFileWriter2.create(schema0, (OutputStream) syncableFileOutputStream0, byteArray0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema$ArraySchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("z\"EX7m[{\"", "\u0006C");
      boolean boolean1 = mockFile0.setReadable(true);
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      String string0 = "9rbUUUj2^(UK";
      String string1 = "5DV{;i<`4";
      GenericDatumWriter<Object> genericDatumWriter0 = new GenericDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter3 = new DataFileWriter<Object>(genericDatumWriter0);
      DataFileWriter<Object> dataFileWriter4 = dataFileWriter3.setMeta("]gn)yzGm!_#^|aHl", 0L);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        dataFileWriter4.append(object0);
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      MockFile mockFile0 = new MockFile("java-key-class");
      File file0 = MockFile.createTempFile("]NM<w.%P~HYwv=", "Mb3RpLG`6f0C4W03yFh", (File) mockFile0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, file0);
      BZip2Codec.Option bZip2Codec_Option0 = new BZip2Codec.Option();
      // Undeclared exception!
      try { 
        dataFileWriter2.setCodec(bZip2Codec_Option0);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      MockFile mockFile0 = new MockFile("avro.java.string");
      MockFile mockFile1 = new MockFile(mockFile0, " _T0IX$rd~A");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(mockFile1);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(syncableFileOutputStream0);
      BinaryEncoder binaryEncoder0 = SpecificData.getEncoder(objectOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(binaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      MockFile mockFile2 = new MockFile("java-key-class");
      File file0 = MockFile.createTempFile("]NM<w.%P~HYwv=", "Mb3RpLGJ6fMC4W03yFh", (File) mockFile2);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, file0);
      FastReaderBuilder.RecordReader fastReaderBuilder_RecordReader0 = new FastReaderBuilder.RecordReader();
      DataFileStream<Object> dataFileStream0 = new DataFileStream<Object>(fastReaderBuilder_RecordReader0);
      // Undeclared exception!
      try { 
        dataFileWriter1.appendAllFrom(dataFileStream0, true);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Json.ObjectWriter json_ObjectWriter0 = new Json.ObjectWriter();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(json_ObjectWriter0);
      Schema schema0 = null;
      Schema schema1 = Protocol.SYSTEM_ERROR;
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      // Undeclared exception!
      try { 
        dataFileWriter0.create(schema1, (OutputStream) pipedOutputStream0);
      } catch(RuntimeException e) {
         //
         // Not the Json schema: \"string\"
         //
         verifyException("org.apache.avro.data.Json$ObjectWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Conversions.BigDecimalConversion conversions_BigDecimalConversion0 = new Conversions.BigDecimalConversion();
      Schema schema0 = conversions_BigDecimalConversion0.getRecommendedSchema();
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ReflectData reflectData0 = new ReflectData(classLoader0);
      Class<Object> class0 = Object.class;
      ReflectData reflectData1 = reflectData0.addStringable(class0);
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>(schema0, reflectData1);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      String string0 = "avro.org.apache.avro.file.DataFileWriter";
      boolean boolean0 = false;
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(datumReader0);
      // Undeclared exception!
      try { 
        dataFileWriter0.appendAllFrom(dataFileStream0, false);
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      LogicalType logicalType0 = new LogicalType("\"#<{rl-}OU}to");
      int int0 = 5;
      Schema schema0 = Schema.createFixed("logicalType", "avro.PROTOCOL", "sync must be exactly 16 bytes", 5);
      Schema schema1 = logicalType0.addToSchema(schema0);
      Schema schema2 = Schema.createArray(schema1);
      LinkedList<Schema.Field> linkedList0 = new LinkedList<Schema.Field>();
      List<Schema.Field> list0 = List.copyOf((Collection<? extends Schema.Field>) linkedList0);
      Schema schema3 = Schema.createRecord("logicalType", "avro.PROTOCOL", "avro.PROTOCOL", true, list0);
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      try { 
        dataFileWriter0.create(schema2, (OutputStream) pipedOutputStream0);
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      MockFile mockFile0 = new MockFile("java-key-class");
      File file0 = MockFile.createTempFile("]NM<w.%P~HYwv=", "Mb3RpLG`6f0C4W03yFh", (File) mockFile0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, file0);
      dataFileWriter2.close();
      dataFileWriter2.close();
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0);
      DataFileWriter<FileOutputStream> dataFileWriter3 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      SeekableFileInput seekableFileInput0 = null;
      try {
        seekableFileInput0 = new SeekableFileInput(mockFile0);
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      DataFileWriter<InputStream> dataFileWriter0 = new DataFileWriter<InputStream>((DatumWriter<InputStream>) null);
      String string0 = null;
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta((String) null, 857L);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)5;
      byteArray0[1] = (byte) (-118);
      byteArray0[2] = (byte)0;
      CodecFactory codecFactory0 = CodecFactory.nullCodec();
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setCodec(codecFactory0);
      dataFileWriter0.close();
      // Undeclared exception!
      try { 
        ByteBuffer.wrap(byteArray0, (int) (byte) (-118), (-1183));
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.ByteBuffer", e);
      }
  }

  @Ignore("Disabled because this EvoSuite-generated test calls DataFileWriter.create with a null schema and is not a stable regression test.")
  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Schema schema0 = null;
      GenericDatumWriter<Object> genericDatumWriter0 = new GenericDatumWriter<Object>((Schema) null);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(genericDatumWriter0);
      String string0 = "FvFlX9OgCn-edn5";
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte) (-67);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("FvFlX9OgCn-edn5", byteArray0);
      String string1 = "9Y1N?4=asG";
      MockFile mockFile0 = new MockFile("9Y1N?4=asG");
      // Undeclared exception!
      try { 
        dataFileWriter1.create((Schema) null, (File) mockFile0);
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/io/IOUtils
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      String string0 = "avro.schema";
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte) (-41);
      byteArray0[2] = (byte)0;
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("avro.schema", byteArray0);
      } catch(RuntimeException e) {
         //
         // Cannot set reserved meta key: avro.schema
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      String string0 = "Z_3zQ463ET}RB(p";
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream("Z_3zQ463ET}RB(p");
      byte[] byteArray0 = new byte[4];
      byteArray0[0] = (byte)3;
      byteArray0[1] = (byte) (-98);
      byteArray0[2] = (byte) (-57);
      byteArray0[3] = (byte) (-4);
      // Undeclared exception!
      try { 
        dataFileWriter0.create((Schema) null, (OutputStream) syncableFileOutputStream0, byteArray0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("java-element-class", "");
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-78);
      byteArray0[1] = (byte) (-27);
      byteArray0[2] = (byte)15;
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.setMeta("java-key-class", byteArray0);
      // Undeclared exception!
      try { 
        dataFileWriter2.sync();
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Schema schema0 = null;
      GenericDatumWriter<Object> genericDatumWriter0 = new GenericDatumWriter<Object>((Schema) null);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(genericDatumWriter0);
      String string0 = null;
      byte[] byteArray0 = new byte[1];
      byte byte0 = (byte) (-63);
      byteArray0[0] = (byte) (-63);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta((String) null, byteArray0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Class<Schema> class0 = Schema.class;
      ReflectDatumWriter<Schema> reflectDatumWriter0 = new ReflectDatumWriter<Schema>(class0);
      DataFileWriter<Schema> dataFileWriter0 = new DataFileWriter<Schema>(reflectDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = ReflectData.get();
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter1 = new DataFileWriter<Object>(reflectDatumWriter1);
      File file0 = MockFile.createTempFile("f=bizQV}9", "java-class");
      try { 
        dataFileWriter1.appendTo(file0);
      } catch(IOException e) {
         //
         // Not an Avro data file.
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      CodecFactory codecFactory0 = CodecFactory.deflateCodec(745);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setCodec(codecFactory0);
      String string0 = "Luy3\"";
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter1.setMeta("org.apache.avro.file.DataFileConstants", "Luy3\"");
      Schema schema0 = Protocol.SYSTEM_ERROR;
      MockPrintStream mockPrintStream0 = new MockPrintStream("already open");
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) reflectDatumWriter0;
      objectArray0[1] = (Object) dataFileWriter0;
      Object object0 = new Object();
      objectArray0[2] = object0;
      PrintStream printStream0 = mockPrintStream0.printf("[dv_ 49syVw68wr k", objectArray0);
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter2.create(schema0, (OutputStream) printStream0);
      // Undeclared exception!
      try { 
        dataFileWriter3.appendTo((SeekableInput) null, (OutputStream) printStream0);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Json.ObjectWriter json_ObjectWriter0 = new Json.ObjectWriter();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(json_ObjectWriter0);
      boolean boolean0 = false;
      dataFileWriter0.setFlushOnEveryBlock(false);
      String string0 = "k$JKH";
      String string1 = "_[}e[%!}";
      try { 
        MockURI.URI("_[}e[%!}", "k$JKH", "k$JKH", 0, "_[}e[%!}", "(4U]^2-_", "w:`P*uVS+5A8");
      } catch(URISyntaxException e) {
         //
         // Relative path in absolute URI: _[}e[%!}://k$JKH@k$JKH:0_%5B%7De%5B%25!%7D?(4U]%5E2-_#w:%60P*uVS+5A8
         //
         verifyException("java.net.URI", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      GenericDatumWriter<Object> genericDatumWriter0 = new GenericDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(genericDatumWriter0);
      Schema schema0 = Schema.createArray((Schema) null);
      File file0 = null;
      // Undeclared exception!
      try { 
        dataFileWriter0.create(schema0, (File) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Schema schema0 = null;
      GenericData genericData0 = new GenericData();
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>((Schema) null, genericData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      String string0 = "";
      MockFile mockFile0 = new MockFile("", "");
      try { 
        dataFileWriter0.create((Schema) null, (File) mockFile0);
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>((DatumWriter<FileOutputStream>) null);
      int int0 = (-1);
      CodecFactory codecFactory0 = CodecFactory.xzCodec((-1));
      // Undeclared exception!
      try { 
        dataFileWriter0.setCodec(codecFactory0);
      } catch(NoClassDefFoundError e) {
         //
         // org/apache/commons/compress/compressors/xz/XZCompressorInputStream
         //
         verifyException("org.apache.avro.file.XZCodec$Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(fileDescriptor0);
      URI uRI0 = MockURI.URI("xz");
      // Undeclared exception!
      try { 
        dataFileWriter0.fSync();
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      ReflectDatumWriter<SeekableFileInput> reflectDatumWriter0 = new ReflectDatumWriter<SeekableFileInput>();
      DataFileWriter<SeekableFileInput> dataFileWriter0 = new DataFileWriter<SeekableFileInput>(reflectDatumWriter0);
      Conversions.UUIDConversion conversions_UUIDConversion0 = new Conversions.UUIDConversion();
      Schema schema0 = conversions_UUIDConversion0.getRecommendedSchema();
      reflectDatumWriter0.setSchema(schema0);
      byte[] byteArray0 = new byte[0];
      DataFileWriter<SeekableFileInput> dataFileWriter1 = dataFileWriter0.setMeta("", byteArray0);
      // Undeclared exception!
      try { 
        dataFileWriter1.fSync();
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>((DatumWriter<FileOutputStream>) null);
      String string0 = "oV\\uSJe3C";
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta(string0, (-1233L));
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter1.setMeta(string0, string0);
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = (byte)49;
      byte byte0 = (byte)0;
      byteArray0[1] = (byte)0;
      byteArray0[2] = (byte)0;
      byteArray0[3] = (byte)12;
      byteArray0[4] = (byte) (-2);
      byteArray0[5] = (byte) (-118);
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter2.setMeta(string0, byteArray0);
      ReflectData reflectData0 = new ReflectData();
      Class<Long> class0 = Long.TYPE;
      Schema schema0 = reflectData0.getSchema(class0);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      // Undeclared exception!
      try { 
        dataFileWriter3.create(schema0, outputStream0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<Object, FileOutputStream>> specificDatumWriter0 = new SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<Object, FileOutputStream>>(schema0);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, FileOutputStream>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, FileOutputStream>>(specificDatumWriter0);
      CodecFactory codecFactory0 = CodecFactory.zstandardCodec((-734), false);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, FileOutputStream>> dataFileWriter1 = dataFileWriter0.setCodec(codecFactory0);
      MockFile mockFile0 = new MockFile("com.fasterxml.jackson.databind.SerializerProvider");
      MockFile mockFile1 = new MockFile(mockFile0, "SSWXk)");
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, FileOutputStream>> dataFileWriter2 = dataFileWriter1.create(schema0, (File) mockFile1);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      // Undeclared exception!
      try { 
        dataFileWriter2.create(schema0, (OutputStream) byteArrayOutputStream0);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      GenericDatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, Object>> genericDatumWriter0 = new GenericDatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, Object>>();
      DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, Object>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, Object>>(genericDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createMap(schema0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(32);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, Object>> dataFileWriter1 = dataFileWriter0.create(schema1, (OutputStream) byteArrayOutputStream0);
      String string0 = "already open";
      // Undeclared exception!
      try { 
        dataFileWriter1.setMeta("already open", "already open");
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Schema.applyAliases(schema0, schema0);
      SpecificData specificData0 = SpecificData.getForSchema(schema0);
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>(schema1, specificData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("", "");
      DataFileReader.SeekableInputStream dataFileReader_SeekableInputStream0 = new DataFileReader.SeekableInputStream((SeekableInput) null);
      MockFile mockFile0 = new MockFile((File) null, "i");
      File file0 = MockFile.createTempFile("java-class", "Cannot use includeAs of ", (File) mockFile0);
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(file0);
      BufferedOutputStream bufferedOutputStream0 = new BufferedOutputStream(syncableFileOutputStream0, 92);
      // Undeclared exception!
      try { 
        dataFileWriter1.appendTo((SeekableInput) dataFileReader_SeekableInputStream0, (OutputStream) bufferedOutputStream0);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileReader$SeekableInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      ReflectData reflectData0 = new ReflectData(classLoader0);
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setSyncInterval(56);
      Conversions.DecimalConversion conversions_DecimalConversion0 = new Conversions.DecimalConversion();
      // Undeclared exception!
      try { 
        conversions_DecimalConversion0.getRecommendedSchema();
      } catch(UnsupportedOperationException e) {
         //
         // No recommended schema for decimal (scale is required)
         //
         verifyException("org.apache.avro.Conversions$DecimalConversion", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>((Schema) null);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      String string0 = null;
      String string1 = "c3YqsKFl[w|>=A}6";
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta((String) null, "c3YqsKFl[w|>=A}6");
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      SpecificDatumWriter<FileOutputStream> specificDatumWriter0 = new SpecificDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(specificDatumWriter0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      Conversions.BigDecimalConversion conversions_BigDecimalConversion0 = new Conversions.BigDecimalConversion();
      BigDecimal bigDecimal0 = BigDecimal.TEN;
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      ReflectData reflectData0 = new ReflectData(classLoader0);
      Schema schema0 = reflectData0.induce(dataFileWriter1);
      LogicalType logicalType0 = schema0.getLogicalType();
      ByteBuffer byteBuffer0 = conversions_BigDecimalConversion0.toBytes(bigDecimal0, schema0, (LogicalType) null);
      // Undeclared exception!
      try { 
        dataFileWriter1.appendEncoded(byteBuffer0);
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("xSPY{C", (-1L));
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      Schema schema1 = Schema.createMap(schema0);
      OutputStream outputStream0 = null;
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte) (-112);
      byteArray0[1] = (byte)111;
      byteArray0[2] = (byte) (-124);
      try { 
        dataFileWriter1.create(schema0, (OutputStream) null, byteArray0);
      } catch(IOException e) {
         //
         // sync must be exactly 16 bytes
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      String string0 = "";
      boolean boolean0 = DataFileWriter.isReservedMeta("");
      Class<Object> class0 = Object.class;
      ReflectData reflectData0 = ReflectData.get();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      String string1 = "I'^g^";
      byte[] byteArray0 = new byte[2];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte)16;
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("I'^g^", byteArray0);
      String string2 = "-Infinity";
      MockFile mockFile0 = new MockFile("-Infinity");
      try { 
        dataFileWriter1.appendTo((File) mockFile0);
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("avro.");
      MockException mockException0 = new MockException("|B0p", mockThrowable0);
      String string0 = mockException0.getLocalizedMessage();
      StackTraceElement[] stackTraceElementArray0 = mockException0.getStackTrace();
      Throwable[] throwableArray0 = mockException0.getSuppressed();
      mockException0.printStackTrace();
      DataFileWriter.AppendWriteException dataFileWriter_AppendWriteException0 = new DataFileWriter.AppendWriteException(mockException0);
      dataFileWriter_AppendWriteException0.setStackTrace(stackTraceElementArray0);
      Throwable throwable0 = dataFileWriter_AppendWriteException0.getCause();
      DataFileWriter.AppendWriteException dataFileWriter_AppendWriteException1 = new DataFileWriter.AppendWriteException(dataFileWriter_AppendWriteException0);
      GenericDatumWriter<Object> genericDatumWriter0 = new GenericDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(genericDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.appendTo((File) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Class<FileOutputStream> class0 = FileOutputStream.class;
      SpecificData specificData0 = SpecificData.getForClass(class0);
      GenericDatumWriter<Object> genericDatumWriter0 = new GenericDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(genericDatumWriter0);
      CodecFactory codecFactory0 = CodecFactory.snappyCodec();
      // Undeclared exception!
      try { 
        dataFileWriter0.setCodec((CodecFactory) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>> specificDatumWriter0 = new SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>>();
      DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>>(specificDatumWriter0);
      byte[] byteArray0 = new byte[5];
      byteArray0[0] = (byte)0;
      byteArray0[1] = (byte)0;
      byteArray0[2] = (byte) (-80);
      byteArray0[3] = (byte) (-35);
      byteArray0[4] = (byte)93;
      SeekableByteArrayInput seekableByteArrayInput0 = new SeekableByteArrayInput(byteArray0);
      DataFileReader.SeekableInputStream dataFileReader_SeekableInputStream0 = new DataFileReader.SeekableInputStream(seekableByteArrayInput0);
      String string0 = "sync must be exactly 16 bytes";
      boolean boolean0 = false;
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream("sync must be exactly 16 bytes", false);
      try { 
        dataFileWriter0.appendTo((SeekableInput) dataFileReader_SeekableInputStream0, (OutputStream) syncableFileOutputStream0);
      } catch(IOException e) {
         //
         // Not an Avro data file.
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      DataFileWriter.AppendWriteException dataFileWriter_AppendWriteException0 = new DataFileWriter.AppendWriteException((Exception) null);
      String string0 = null;
      // Undeclared exception!
      try { 
        DataFileWriter.isReservedMeta((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      SpecificData specificData0 = new SpecificData();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      File file0 = MockFile.createTempFile("org.apache.avro.fastread", "-z5!5e");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(file0);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) syncableFileOutputStream0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      byte[] byteArray0 = new byte[6];
      byteArray0[0] = (byte)113;
      byteArray0[1] = (byte)0;
      byteArray0[2] = (byte)79;
      byteArray0[3] = (byte)127;
      byteArray0[4] = (byte) (-27);
      byteArray0[5] = (byte)0;
      // Undeclared exception!
      try { 
        dataFileWriter1.create(schema1, (OutputStream) syncableFileOutputStream0, byteArray0);
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.flush();
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Schema schema0 = null;
      ReflectData reflectData0 = ReflectData.get();
      SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> specificDatumWriter0 = new SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<Object, Object>>((Schema) null, reflectData0);
      DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<Object, Object>>(specificDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("avro.java.string", 0L);
      } catch(RuntimeException e) {
         //
         // Cannot set reserved meta key: avro.java.string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      Object object0 = new Object();
      byte[] byteArray0 = reflectDatumWriter0.toByteArray(object0);
      byte[] byteArray1 = reflectDatumWriter0.toByteArray(object0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.flush();
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Class<FileOutputStream> class0 = FileOutputStream.class;
      ReflectData reflectData0 = new ReflectData((ClassLoader) null);
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(class0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      ZstandardCodec.Option zstandardCodec_Option0 = new ZstandardCodec.Option(2, true, true);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setCodec(zstandardCodec_Option0);
      FileDescriptor fileDescriptor0 = new FileDescriptor();
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(fileDescriptor0);
      DataFileReader.SeekableInputStream dataFileReader_SeekableInputStream0 = new DataFileReader.SeekableInputStream(seekableFileInput0);
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream("java-class", false);
      MockPrintStream mockPrintStream0 = new MockPrintStream(syncableFileOutputStream0);
      try { 
        dataFileWriter1.appendTo((SeekableInput) dataFileReader_SeekableInputStream0, (OutputStream) mockPrintStream0);
      } catch(IOException e) {
         //
         // Not an Avro data file.
         //
         verifyException("org.apache.avro.file.DataFileStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createMap(schema0);
      // Undeclared exception!
      try { 
        dataFileWriter0.create(schema1, (OutputStream) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Schema schema0 = null;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>((Schema) null);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      String string0 = "";
      String string1 = "No mixed type map values.";
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("", "No mixed type map values.");
      String string2 = "Y";
      // Undeclared exception!
      try { 
        MockFile.createTempFile("", "Y");
      } catch(IllegalArgumentException e) {
         //
         // Prefix string too short
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      MockException mockException0 = new MockException("cdmG");
      MockException mockException1 = new MockException(mockException0);
      DataFileWriter.AppendWriteException dataFileWriter_AppendWriteException0 = new DataFileWriter.AppendWriteException(mockException1);
      Throwable throwable0 = dataFileWriter_AppendWriteException0.fillInStackTrace();
      MockException mockException2 = new MockException("*0J+INFI_49f;E6yfTo", throwable0);
      DataFileWriter.AppendWriteException dataFileWriter_AppendWriteException1 = new DataFileWriter.AppendWriteException(mockException2);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      boolean boolean0 = dataFileWriter0.isFlushOnEveryBlock();
      String string0 = "";
      String string1 = null;
      int int0 = 1627;
      // Undeclared exception!
      try { 
        Schema.createFixed("", "", (String) null, 1627);
      } catch(RuntimeException e) {
         //
         // Empty name
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval((-807));
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: -807
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "java-key-class");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter3 = new DataFileWriter<Object>(reflectDatumWriter1);
      DataFileWriter<Object> dataFileWriter4 = dataFileWriter3.setMeta("org.apache.avro.fastread", "avro.java.string");
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter4.appendTo((File) mockFile0);
      Random.setNextRandom(990);
      dataFileWriter3.fSync();
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "\u0006C");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter0.create(schema0, (OutputStream) mockPrintStream0);
      dataFileWriter1.fSync();
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockPrintStream0);
      BinaryEncoder binaryEncoder0 = SpecificData.getEncoder(objectOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      byte[] byteArray0 = new byte[4];
      ReflectDatumWriter<Object> reflectDatumWriter1 = new ReflectDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter3 = new DataFileWriter<Object>(reflectDatumWriter1);
      ZstandardCodec.Option zstandardCodec_Option0 = new ZstandardCodec.Option((byte)0, false, false);
      DataFileWriter<Object> dataFileWriter4 = dataFileWriter3.setCodec(zstandardCodec_Option0);
      DataFileWriter<Object> dataFileWriter5 = dataFileWriter3.appendTo((File) mockFile0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>((DatumWriter<FileOutputStream>) null);
      XZCodec.Option xZCodec_Option0 = new XZCodec.Option((-1));
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval(6);
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: 6
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
      byte[] byteArray0 = new byte[12];
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      try { 
        dataFileWriter0.create(schema0, (OutputStream) byteArrayOutputStream0, byteArray0);
      } catch(IOException e) {
         //
         // sync must be exactly 16 bytes
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp");
      boolean boolean0 = FileSystemHandling.appendStringToFile(evoSuiteFile0, "sync must be exactly 16 bytes");
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      MockFile mockFile0 = new MockFile("sync must be exactly 16 bytes", "4SnLm=&e");
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream(mockFile0, false);
      byte[] byteArray0 = new byte[16];
      byteArray0[0] = (byte)82;
      byteArray0[1] = (byte)82;
      byteArray0[2] = (byte)94;
      byteArray0[6] = (byte)70;
      byteArray0[13] = (byte)82;
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter0.setSyncInterval((byte)82);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = charset0.encode("sync must be exactly 16 bytes");
      ReflectData reflectData0 = ReflectData.get();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter1 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter3 = new DataFileWriter<FileOutputStream>(reflectDatumWriter1);
      NullCodec.Option nullCodec_Option0 = (NullCodec.Option)NullCodec.OPTION;
      DataFileWriter<FileOutputStream> dataFileWriter4 = dataFileWriter3.setCodec(nullCodec_Option0);
      DataFileWriter<FileOutputStream> dataFileWriter5 = dataFileWriter4.setSyncInterval((byte)70);
      DataFileWriter<FileOutputStream> dataFileWriter6 = dataFileWriter5.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      DataFileWriter<FileOutputStream> dataFileWriter7 = dataFileWriter6.setEncoder(function0);
      dataFileWriter7.fSync();
      Random.setNextRandom((-1115));
      dataFileWriter2.appendEncoded(byteBuffer0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("4SnLm=&e", "4SnLm=&e");
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>> specificDatumWriter0 = new SpecificDatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>>();
      DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>>(specificDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("avro.*xCrt,M)Z0{`In", "avro.*xCrt,M)Z0{`In");
      } catch(RuntimeException e) {
         //
         // Cannot set reserved meta key: avro.*xCrt,M)Z0{`In
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      SpecificData specificData0 = SpecificData.get();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, specificData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      MockFile mockFile0 = new MockFile("java-class", "avro.java.string");
      SyncableFileOutputStream syncableFileOutputStream0 = new SyncableFileOutputStream(mockFile0);
      BlockingDirectBinaryEncoder blockingDirectBinaryEncoder0 = new BlockingDirectBinaryEncoder(syncableFileOutputStream0);
      Function<OutputStream, BinaryEncoder> function0 = (Function<OutputStream, BinaryEncoder>) mock(Function.class, new ViolatedAssumptionAnswer());
      doReturn(blockingDirectBinaryEncoder0).when(function0).apply(any(java.io.OutputStream.class));
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setEncoder(function0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, (File) mockFile0);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = charset0.encode("java-element-class");
      dataFileWriter2.appendEncoded(byteBuffer0);
      dataFileWriter2.close();
      DataFileWriter<Object> dataFileWriter3 = dataFileWriter1.setSyncInterval(1246);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream();
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      ReflectDatumWriter<SeekableFileInput> reflectDatumWriter0 = new ReflectDatumWriter<SeekableFileInput>();
      DataFileWriter<SeekableFileInput> dataFileWriter0 = new DataFileWriter<SeekableFileInput>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval(1073741834);
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: 1073741834
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectData reflectData0 = new ReflectData();
      boolean boolean0 = FileSystemHandling.shouldAllThrowIOExceptions();
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0, reflectData0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setMeta("org.apache.avro.fastread", "avro.java.string");
      MockFile mockFile0 = new MockFile("java-class", "java-key-class");
      String string0 = "9rbUU!j2(UK";
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(datumReader0);
      // Undeclared exception!
      try { 
        dataFileWriter1.appendAllFrom(dataFileStream0, true);
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }
}
