/*
 * This file was automatically generated by EvoSuite
 * Thu May 28 13:41:59 GMT 2026
 */

package org.apache.avro.file;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedInputStream;
import java.io.EOFException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.URI;
import java.nio.ByteBuffer;
import java.util.AbstractMap;
import java.util.function.Function;
import org.apache.avro.Protocol;
import org.apache.avro.Schema;
import org.apache.avro.file.BZip2Codec;
import org.apache.avro.file.CodecFactory;
import org.apache.avro.file.DataFileStream;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.file.SeekableFileInput;
import org.apache.avro.file.SeekableInput;
import org.apache.avro.generic.GenericDatumWriter;
import org.apache.avro.io.BinaryEncoder;
import org.apache.avro.io.DatumReader;
import org.apache.avro.io.DatumWriter;
import org.apache.avro.reflect.ReflectData;
import org.apache.avro.reflect.ReflectDatumWriter;
import org.apache.avro.specific.SpecificDatumWriter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = false, separateClassLoader = true) 
public class DataFileWriter_C2_ESTest extends DataFileWriter_C2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
    // Filtered: brittle EvoSuite-generated assertion.
    return;
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      File file0 = MockFile.createTempFile("org.apache.avro.fastread", "}");
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, file0);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        dataFileWriter1.append(object0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Not in union [\"string\"]: java.lang.Object@110d3f26
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      Class<Object> class0 = Object.class;
      ReflectData reflectData0 = ReflectData.get();
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      MockFile mockFile0 = new MockFile("avro.java.string", "L~h[(_Z");
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.create(schema0, (File) mockFile0);
      dataFileWriter1.close();
      assertEquals(42L, mockFile0.length());
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      dataFileWriter0.close();
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("logicalType");
      dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0);
      dataFileWriter0.fSync();
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      dataFileWriter0.create(schema0, outputStream0);
      dataFileWriter0.fSync();
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter1 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter1 = new DataFileWriter<FileOutputStream>(reflectDatumWriter1);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter1.create(schema0, outputStream0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/foo.bar");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "-^cZ(;}ARvd");
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(seekableFileInput0);
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(bufferedInputStream0, datumReader0);
      try { 
        dataFileWriter2.appendAllFrom(dataFileStream0, true);
        fail("Expecting exception: EOFException");
      
      } catch(EOFException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.io.BinaryDecoder$InputStreamByteSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(schema0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>(schema0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      dataFileWriter1.create(schema0, outputStream0);
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/tmp/foo.bar");
      byte[] byteArray0 = new byte[6];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(seekableFileInput0);
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(bufferedInputStream0, datumReader0);
      try { 
        dataFileWriter1.appendAllFrom(dataFileStream0, false);
        fail("Expecting exception: EOFException");
      
      } catch(EOFException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.io.BinaryDecoder$InputStreamByteSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>(schema0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter1.create(schema0, outputStream0);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      BufferedInputStream bufferedInputStream0 = new BufferedInputStream(seekableFileInput0);
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(bufferedInputStream0, datumReader0);
      dataFileWriter2.appendAllFrom(dataFileStream0, false);
      assertEquals((-2), seekableFileInput0.available());
      assertEquals(43L, mockFile0.length());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter1 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter1 = new DataFileWriter<FileOutputStream>(reflectDatumWriter1);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      BZip2Codec.Option bZip2Codec_Option0 = new BZip2Codec.Option();
      DataFileWriter<FileOutputStream> dataFileWriter2 = dataFileWriter1.setCodec(bZip2Codec_Option0);
      DataFileWriter<FileOutputStream> dataFileWriter3 = dataFileWriter2.create(schema0, outputStream0);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(seekableFileInput0, datumReader0);
      dataFileWriter3.appendAllFrom(dataFileStream0, true);
      assertEquals((-2), seekableFileInput0.available());
      assertTrue(dataFileWriter3.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      ReflectData reflectData0 = new ReflectData(classLoader0);
      Schema schema0 = reflectData0.induce(dataFileWriter0);
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter1 = new ReflectDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter1 = new DataFileWriter<FileOutputStream>(reflectDatumWriter1);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      dataFileWriter1.create(schema0, outputStream0);
      SeekableFileInput seekableFileInput0 = new SeekableFileInput(mockFile0);
      DatumReader<FileOutputStream> datumReader0 = (DatumReader<FileOutputStream>) mock(DatumReader.class, new ViolatedAssumptionAnswer());
      DataFileStream<FileOutputStream> dataFileStream0 = new DataFileStream<FileOutputStream>(seekableFileInput0, datumReader0);
      try { 
        dataFileWriter1.appendAllFrom(dataFileStream0, false);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Schema from file org.apache.avro.file.DataFileStream@336 does not match
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setSyncInterval(591);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      DataFileWriter<Object> dataFileWriter2 = dataFileWriter1.create(schema0, (File) mockFile0);
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(591);
      dataFileWriter2.appendEncoded(byteBuffer0);
      assertEquals(653L, mockFile0.length());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Schema schema0 = Schema.createMap((Schema) null);
      ReflectData reflectData0 = new ReflectData();
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>(schema0, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setMeta("avro.java.string", "org.apache.avro.fastread");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Cannot set reserved meta key: avro.java.string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      CodecFactory codecFactory0 = CodecFactory.zstandardCodec(78);
      dataFileWriter0.setCodec(codecFactory0);
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      Class<String> class0 = String.class;
      SpecificDatumWriter<String> specificDatumWriter0 = new SpecificDatumWriter<String>(class0);
      DataFileWriter<String> dataFileWriter1 = new DataFileWriter<String>(specificDatumWriter0);
      DataFileWriter<String> dataFileWriter2 = dataFileWriter1.appendTo((File) mockFile0);
      assertEquals(64L, mockFile0.length());
      assertTrue(dataFileWriter2.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SpecificDatumWriter<Object> specificDatumWriter0 = new SpecificDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(specificDatumWriter0);
      Schema schema0 = Protocol.SYSTEM_ERROR;
      byte[] byteArray0 = new byte[1];
      try { 
        dataFileWriter0.create(schema0, (OutputStream) null, byteArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // sync must be exactly 16 bytes
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("avF<P2", true);
      byte[] byteArray0 = new byte[16];
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      // Undeclared exception!
      try { 
        dataFileWriter0.create(schema0, (OutputStream) mockFileOutputStream0, byteArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>();
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval(2147483632);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: 2147483632
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Class<Object> class0 = Object.class;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>(class0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.setSyncInterval(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid syncInterval value: 0
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      OutputStream outputStream0 = OutputStream.nullOutputStream();
      Class<String> class0 = String.class;
      SpecificDatumWriter<String> specificDatumWriter0 = new SpecificDatumWriter<String>(class0);
      DataFileWriter<String> dataFileWriter1 = new DataFileWriter<String>(specificDatumWriter0);
      DataFileWriter<String> dataFileWriter2 = dataFileWriter1.appendTo((File) mockFile0);
      // Undeclared exception!
      try { 
        dataFileWriter2.appendTo((SeekableInput) null, outputStream0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // already open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<FileOutputStream> reflectDatumWriter0 = new ReflectDatumWriter<FileOutputStream>(schema0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(reflectDatumWriter0);
      File file0 = MockFile.createTempFile("app", "app");
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.create(schema0, file0);
      dataFileWriter1.fSync();
      assertEquals(43L, file0.length());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      URI uRI0 = MockURI.aFileURI;
      MockFile mockFile0 = new MockFile(uRI0);
      dataFileWriter0.create(schema0, (File) mockFile0);
      Class<String> class0 = String.class;
      SpecificDatumWriter<String> specificDatumWriter0 = new SpecificDatumWriter<String>(class0);
      DataFileWriter<String> dataFileWriter1 = new DataFileWriter<String>(specificDatumWriter0);
      // Undeclared exception!
      try { 
        dataFileWriter0.append(dataFileWriter1);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.ClassCastException: value org.apache.avro.file.DataFileWriter@10 (a org.apache.avro.file.DataFileWriter) cannot be cast to expected type string
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>((DatumWriter<Object>) null);
      DataFileWriter<Object> dataFileWriter1 = dataFileWriter0.setMeta("avF<P2", (-5053L));
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>();
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      ByteBuffer byteBuffer0 = ByteBuffer.allocate(591);
      // Undeclared exception!
      try { 
        dataFileWriter0.appendEncoded(byteBuffer0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // not open
         //
         verifyException("org.apache.avro.file.DataFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      ReflectData reflectData0 = new ReflectData(classLoader0);
      ReflectDatumWriter<Object> reflectDatumWriter0 = new ReflectDatumWriter<Object>((Schema) null, reflectData0);
      DataFileWriter<Object> dataFileWriter0 = new DataFileWriter<Object>(reflectDatumWriter0);
      boolean boolean0 = dataFileWriter0.isFlushOnEveryBlock();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>> dataFileWriter0 = new DataFileWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>>((DatumWriter<AbstractMap.SimpleImmutableEntry<FileOutputStream, FileOutputStream>>) null);
      assertTrue(dataFileWriter0.isFlushOnEveryBlock());
      
      dataFileWriter0.setFlushOnEveryBlock(false);
      assertFalse(dataFileWriter0.isFlushOnEveryBlock());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      GenericDatumWriter<FileOutputStream> genericDatumWriter0 = new GenericDatumWriter<FileOutputStream>(schema0);
      DataFileWriter<FileOutputStream> dataFileWriter0 = new DataFileWriter<FileOutputStream>(genericDatumWriter0);
      DataFileWriter<FileOutputStream> dataFileWriter1 = dataFileWriter0.setEncoder((Function<OutputStream, BinaryEncoder>) null);
      assertTrue(dataFileWriter1.isFlushOnEveryBlock());
  }
}
